#include "EffectAbilityAcc.cpp"
#include "EffectArmorAcc.cpp"
#include "EffectAttackAcc.cpp"
//#include "EffectDamageAcc.cpp"
#include "EffectImmunityAcc.cpp"
#include "EffectSaveAcc.cpp"
#include "EffectSkillAcc.cpp"
