/*
 *  NWNeXalt - Empty File
 *  (c) 2007 Doug Swarin (zac@intertex.net)
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 *  $Id$
 *  $HeadURL$
 *
 */

#ifndef _NX_NWN_CONST_SPELLS_H_
#define _NX_NWN_CONST_SPELLS_H_

#define SPELL_SCHOOL_GENERAL       0
#define SPELL_SCHOOL_ABJURATION    1
#define SPELL_SCHOOL_CONJURATION   2
#define SPELL_SCHOOL_DIVINATION    3
#define SPELL_SCHOOL_ENCHANTMENT   4
#define SPELL_SCHOOL_EVOCATION     5
#define SPELL_SCHOOL_ILLUSION      6
#define SPELL_SCHOOL_NECROMANCY    7
#define SPELL_SCHOOL_TRANSMUTATION 8

#define SPELL_ALL_SPELLS                               -1
#define SPELL_ACID_FOG                                 0
#define SPELL_AID                                      1
#define SPELL_ANIMATE_DEAD                             2
#define SPELL_BARKSKIN                                 3
#define SPELL_BESTOW_CURSE                             4
#define SPELL_BLADE_BARRIER                            5
#define SPELL_BLESS                                    6
#define SPELL_BLESS_WEAPON                             537
#define SPELL_BLINDNESS_AND_DEAFNESS                   8
#define SPELL_BULLS_STRENGTH                           9
#define SPELL_BURNING_HANDS                            10
#define SPELL_CALL_LIGHTNING                           11
#define SPELL_CATS_GRACE                               13
#define SPELL_CHAIN_LIGHTNING                          14
#define SPELL_CHARM_MONSTER                            15
#define SPELL_CHARM_PERSON                             16
#define SPELL_CHARM_PERSON_OR_ANIMAL                   17
#define SPELL_CIRCLE_OF_DEATH                          18
#define SPELL_CIRCLE_OF_DOOM                           19
#define SPELL_CLAIRAUDIENCE_AND_CLAIRVOYANCE           20
#define SPELL_CLARITY                                  21
#define SPELL_CLOAK_OF_CHAOS                           22
#define SPELL_CLOUDKILL                                23
#define SPELL_COLOR_SPRAY                              24
#define SPELL_CONE_OF_COLD                             25
#define SPELL_CONFUSION                                26
#define SPELL_CONTAGION                                27
#define SPELL_CONTROL_UNDEAD                           28
#define SPELL_CREATE_GREATER_UNDEAD                    29
#define SPELL_CREATE_UNDEAD                            30
#define SPELL_CURE_CRITICAL_WOUNDS                     31
#define SPELL_CURE_LIGHT_WOUNDS                        32
#define SPELL_CURE_MINOR_WOUNDS                        33
#define SPELL_CURE_MODERATE_WOUNDS                     34
#define SPELL_CURE_SERIOUS_WOUNDS                      35
#define SPELL_DARKNESS                                 36
#define SPELL_DAZE                                     37
#define SPELL_DEATH_WARD                               38
#define SPELL_DELAYED_BLAST_FIREBALL                   39
#define SPELL_DISMISSAL                                40
#define SPELL_DISPEL_MAGIC                             41
#define SPELL_DIVINE_POWER                             42
#define SPELL_DOMINATE_ANIMAL                          43
#define SPELL_DOMINATE_MONSTER                         44
#define SPELL_DOMINATE_PERSON                          45
#define SPELL_DOOM                                     46
#define SPELL_ELEMENTAL_SHIELD                         47
#define SPELL_ELEMENTAL_SWARM                          48
#define SPELL_ENDURANCE                                49
#define SPELL_ENDURE_ELEMENTS                          50
#define SPELL_ENERGY_DRAIN                             51
#define SPELL_ENERVATION                               52
#define SPELL_ENTANGLE                                 53
#define SPELL_FEAR                                     54
#define SPELL_FEEBLEMIND                               55
#define SPELL_FINGER_OF_DEATH                          56
#define SPELL_FIRE_STORM                               57
#define SPELL_FIREBALL                                 58
#define SPELL_FLAME_ARROW                              59
#define SPELL_FLAME_LASH                               60
#define SPELL_FLAME_STRIKE                             61
#define SPELL_FREEDOM_OF_MOVEMENT                      62
#define SPELL_GATE                                     63
#define SPELL_GHOUL_TOUCH                              64
#define SPELL_GLOBE_OF_INVULNERABILITY                 65
#define SPELL_GREASE                                   66
#define SPELL_GREATER_DISPELLING                       67
#define SPELL_GREATER_PLANAR_BINDING                   69
#define SPELL_GREATER_RESTORATION                      70
#define SPELL_GREATER_SPELL_BREACH                     72
#define SPELL_GREATER_SPELL_MANTLE                     73
#define SPELL_GREATER_STONESKIN                        74
#define SPELL_GUST_OF_WIND                             75
#define SPELL_HAMMER_OF_THE_GODS                       76
#define SPELL_HARM                                     77
#define SPELL_HASTE                                    78
#define SPELL_HEAL                                     79
#define SPELL_HEALING_CIRCLE                           80
#define SPELL_HOLD_ANIMAL                              81
#define SPELL_HOLD_MONSTER                             82
#define SPELL_HOLD_PERSON                              83
#define SPELL_HOLY_AURA                                84
#define SPELL_HOLY_SWORD                               538
#define SPELL_IDENTIFY                                 86
#define SPELL_IMPLOSION                                87
#define SPELL_IMPROVED_INVISIBILITY                    88
#define SPELL_INCENDIARY_CLOUD                         89
#define SPELL_INVISIBILITY                             90
#define SPELL_INVISIBILITY_PURGE                       91
#define SPELL_INVISIBILITY_SPHERE                      92
#define SPELL_KNOCK                                    93
#define SPELL_LESSER_DISPEL                            94
#define SPELL_LESSER_MIND_BLANK                        95
#define SPELL_LESSER_PLANAR_BINDING                    96
#define SPELL_LESSER_RESTORATION                       97
#define SPELL_LESSER_SPELL_BREACH                      98
#define SPELL_LESSER_SPELL_MANTLE                      99
#define SPELL_LIGHT                                    100
#define SPELL_LIGHTNING_BOLT                           101
#define SPELL_MAGE_ARMOR                               102
#define SPELL_MAGIC_CIRCLE_AGAINST_CHAOS               103
#define SPELL_MAGIC_CIRCLE_AGAINST_EVIL                104
#define SPELL_MAGIC_CIRCLE_AGAINST_GOOD                105
#define SPELL_MAGIC_CIRCLE_AGAINST_LAW                 106
#define SPELL_MAGIC_MISSILE                            107
#define SPELL_MAGIC_VESTMENT                           546
#define SPELL_MASS_BLINDNESS_AND_DEAFNESS              110
#define SPELL_MASS_CHARM                               111
#define SPELL_MASS_HASTE                               113
#define SPELL_MASS_HEAL                                114
#define SPELL_MELFS_ACID_ARROW                         115
#define SPELL_METEOR_SWARM                             116
#define SPELL_MIND_BLANK                               117
#define SPELL_MIND_FOG                                 118
#define SPELL_MINOR_GLOBE_OF_INVULNERABILITY           119
#define SPELL_GHOSTLY_VISAGE                           120
#define SPELL_ETHEREAL_VISAGE                          121
#define SPELL_MORDENKAINENS_DISJUNCTION                122
#define SPELL_MORDENKAINENS_SWORD                      123
#define SPELL_NATURES_BALANCE                          124
#define SPELL_NEGATIVE_ENERGY_PROTECTION               125
#define SPELL_NEUTRALIZE_POISON                        126
#define SPELL_PHANTASMAL_KILLER                        127
#define SPELL_PLANAR_BINDING                           128
#define SPELL_POISON                                   129
#define SPELL_POLYMORPH_SELF                           130
#define SPELL_POWER_WORD_KILL                          131
#define SPELL_POWER_WORD_STUN                          132
#define SPELL_PRAYER                                   133
#define SPELL_PREMONITION                              134
#define SPELL_PRISMATIC_SPRAY                          135
#define SPELL_PROTECTION__FROM_CHAOS                   136
#define SPELL_PROTECTION_FROM_ELEMENTS                 137
#define SPELL_PROTECTION_FROM_EVIL                     138
#define SPELL_PROTECTION_FROM_GOOD                     139
#define SPELL_PROTECTION_FROM_LAW                      140
#define SPELL_PROTECTION_FROM_SPELLS                   141
#define SPELL_RAISE_DEAD                               142
#define SPELL_RAY_OF_ENFEEBLEMENT                      143
#define SPELL_RAY_OF_FROST                             144
#define SPELL_REMOVE_BLINDNESS_AND_DEAFNESS            145
#define SPELL_REMOVE_CURSE                             146
#define SPELL_REMOVE_DISEASE                           147
#define SPELL_REMOVE_FEAR                              148
#define SPELL_REMOVE_PARALYSIS                         149
#define SPELL_RESIST_ELEMENTS                          150
#define SPELL_RESISTANCE                               151
#define SPELL_RESTORATION                              152
#define SPELL_RESURRECTION                             153
#define SPELL_SANCTUARY                                154
#define SPELL_SCARE                                    155
#define SPELL_SEARING_LIGHT                            156
#define SPELL_SEE_INVISIBILITY                         157
#define SPELL_SHADOW_SHIELD                            160
#define SPELL_SHAPECHANGE                              161
#define SPELL_SHIELD_OF_LAW                            162
#define SPELL_SILENCE                                  163
#define SPELL_SLAY_LIVING                              164
#define SPELL_SLEEP                                    165
#define SPELL_SLOW                                     166
#define SPELL_SOUND_BURST                              167
#define SPELL_SPELL_RESISTANCE                         168
#define SPELL_SPELL_MANTLE                             169
#define SPELL_SPHERE_OF_CHAOS                          170
#define SPELL_STINKING_CLOUD                           171
#define SPELL_STONESKIN                                172
#define SPELL_STORM_OF_VENGEANCE                       173
#define SPELL_SUMMON_CREATURE_I                        174
#define SPELL_SUMMON_CREATURE_II                       175
#define SPELL_SUMMON_CREATURE_III                      176
#define SPELL_SUMMON_CREATURE_IV                       177
#define SPELL_SUMMON_CREATURE_IX                       178
#define SPELL_SUMMON_CREATURE_V                        179
#define SPELL_SUMMON_CREATURE_VI                       180
#define SPELL_SUMMON_CREATURE_VII                      181
#define SPELL_SUMMON_CREATURE_VIII                     182
#define SPELL_SUNBEAM                                  183
#define SPELL_TENSERS_TRANSFORMATION                   184
#define SPELL_TIME_STOP                                185
#define SPELL_TRUE_SEEING                              186
#define SPELL_UNHOLY_AURA                              187
#define SPELL_VAMPIRIC_TOUCH                           188
#define SPELL_VIRTUE                                   189
#define SPELL_WAIL_OF_THE_BANSHEE                      190
#define SPELL_WALL_OF_FIRE                             191
#define SPELL_WEB                                      192
#define SPELL_WEIRD                                    193
#define SPELL_WORD_OF_FAITH                            194
#define SPELLABILITY_AURA_BLINDING                     195
#define SPELLABILITY_AURA_COLD                         196
#define SPELLABILITY_AURA_ELECTRICITY                  197
#define SPELLABILITY_AURA_FEAR                         198
#define SPELLABILITY_AURA_FIRE                         199
#define SPELLABILITY_AURA_MENACE                       200
#define SPELLABILITY_AURA_PROTECTION                   201
#define SPELLABILITY_AURA_STUN                         202
#define SPELLABILITY_AURA_UNEARTHLY_VISAGE             203
#define SPELLABILITY_AURA_UNNATURAL                    204
#define SPELLABILITY_BOLT_ABILITY_DRAIN_CHARISMA       205
#define SPELLABILITY_BOLT_ABILITY_DRAIN_CONSTITUTION   206
#define SPELLABILITY_BOLT_ABILITY_DRAIN_DEXTERITY      207
#define SPELLABILITY_BOLT_ABILITY_DRAIN_INTELLIGENCE   208
#define SPELLABILITY_BOLT_ABILITY_DRAIN_STRENGTH       209
#define SPELLABILITY_BOLT_ABILITY_DRAIN_WISDOM         210
#define SPELLABILITY_BOLT_ACID                         211
#define SPELLABILITY_BOLT_CHARM                        212
#define SPELLABILITY_BOLT_COLD                         213
#define SPELLABILITY_BOLT_CONFUSE                      214
#define SPELLABILITY_BOLT_DAZE                         215
#define SPELLABILITY_BOLT_DEATH                        216
#define SPELLABILITY_BOLT_DISEASE                      217
#define SPELLABILITY_BOLT_DOMINATE                     218
#define SPELLABILITY_BOLT_FIRE                         219
#define SPELLABILITY_BOLT_KNOCKDOWN                    220
#define SPELLABILITY_BOLT_LEVEL_DRAIN                  221
#define SPELLABILITY_BOLT_LIGHTNING                    222
#define SPELLABILITY_BOLT_PARALYZE                     223
#define SPELLABILITY_BOLT_POISON                       224
#define SPELLABILITY_BOLT_SHARDS                       225
#define SPELLABILITY_BOLT_SLOW                         226
#define SPELLABILITY_BOLT_STUN                         227
#define SPELLABILITY_BOLT_WEB                          228
#define SPELLABILITY_CONE_ACID                         229
#define SPELLABILITY_CONE_COLD                         230
#define SPELLABILITY_CONE_DISEASE                      231
#define SPELLABILITY_CONE_FIRE                         232
#define SPELLABILITY_CONE_LIGHTNING                    233
#define SPELLABILITY_CONE_POISON                       234
#define SPELLABILITY_CONE_SONIC                        235
#define SPELLABILITY_DRAGON_BREATH_ACID                236
#define SPELLABILITY_DRAGON_BREATH_COLD                237
#define SPELLABILITY_DRAGON_BREATH_FEAR                238
#define SPELLABILITY_DRAGON_BREATH_FIRE                239
#define SPELLABILITY_DRAGON_BREATH_GAS                 240
#define SPELLABILITY_DRAGON_BREATH_LIGHTNING           241
#define SPELLABILITY_DRAGON_BREATH_PARALYZE            242
#define SPELLABILITY_DRAGON_BREATH_SLEEP               243
#define SPELLABILITY_DRAGON_BREATH_SLOW                244
#define SPELLABILITY_DRAGON_BREATH_WEAKEN              245
#define SPELLABILITY_DRAGON_WING_BUFFET                246
#define SPELLABILITY_FEROCITY_1                        247
#define SPELLABILITY_FEROCITY_2                        248
#define SPELLABILITY_FEROCITY_3                        249
#define SPELLABILITY_GAZE_CHARM                        250
#define SPELLABILITY_GAZE_CONFUSION                    251
#define SPELLABILITY_GAZE_DAZE                         252
#define SPELLABILITY_GAZE_DEATH                        253
#define SPELLABILITY_GAZE_DESTROY_CHAOS                254
#define SPELLABILITY_GAZE_DESTROY_EVIL                 255
#define SPELLABILITY_GAZE_DESTROY_GOOD                 256
#define SPELLABILITY_GAZE_DESTROY_LAW                  257
#define SPELLABILITY_GAZE_DOMINATE                     258
#define SPELLABILITY_GAZE_DOOM                         259
#define SPELLABILITY_GAZE_FEAR                         260
#define SPELLABILITY_GAZE_PARALYSIS                    261
#define SPELLABILITY_GAZE_STUNNED                      262
#define SPELLABILITY_GOLEM_BREATH_GAS                  263
#define SPELLABILITY_HELL_HOUND_FIREBREATH             264
#define SPELLABILITY_HOWL_CONFUSE                      265
#define SPELLABILITY_HOWL_DAZE                         266
#define SPELLABILITY_HOWL_DEATH                        267
#define SPELLABILITY_HOWL_DOOM                         268
#define SPELLABILITY_HOWL_FEAR                         269
#define SPELLABILITY_HOWL_PARALYSIS                    270
#define SPELLABILITY_HOWL_SONIC                        271
#define SPELLABILITY_HOWL_STUN                         272
#define SPELLABILITY_INTENSITY_1                       273
#define SPELLABILITY_INTENSITY_2                       274
#define SPELLABILITY_INTENSITY_3                       275
#define SPELLABILITY_KRENSHAR_SCARE                    276
#define SPELLABILITY_LESSER_BODY_ADJUSTMENT            277
#define SPELLABILITY_MEPHIT_SALT_BREATH                278
#define SPELLABILITY_MEPHIT_STEAM_BREATH               279
#define SPELLABILITY_MUMMY_BOLSTER_UNDEAD              280
#define SPELLABILITY_PULSE_DROWN                       281
#define SPELLABILITY_PULSE_SPORES                      282
#define SPELLABILITY_PULSE_WHIRLWIND                   283
#define SPELLABILITY_PULSE_FIRE                        284
#define SPELLABILITY_PULSE_LIGHTNING                   285
#define SPELLABILITY_PULSE_COLD                        286
#define SPELLABILITY_PULSE_NEGATIVE                    287
#define SPELLABILITY_PULSE_HOLY                        288
#define SPELLABILITY_PULSE_DEATH                       289
#define SPELLABILITY_PULSE_LEVEL_DRAIN                 290
#define SPELLABILITY_PULSE_ABILITY_DRAIN_INTELLIGENCE  291
#define SPELLABILITY_PULSE_ABILITY_DRAIN_CHARISMA      292
#define SPELLABILITY_PULSE_ABILITY_DRAIN_CONSTITUTION  293
#define SPELLABILITY_PULSE_ABILITY_DRAIN_DEXTERITY     294
#define SPELLABILITY_PULSE_ABILITY_DRAIN_STRENGTH      295
#define SPELLABILITY_PULSE_ABILITY_DRAIN_WISDOM        296
#define SPELLABILITY_PULSE_POISON                      297
#define SPELLABILITY_PULSE_DISEASE                     298
#define SPELLABILITY_RAGE_3                            299
#define SPELLABILITY_RAGE_4                            300
#define SPELLABILITY_RAGE_5                            301
#define SPELLABILITY_SMOKE_CLAW                        302
#define SPELLABILITY_SUMMON_SLAAD                      303
#define SPELLABILITY_SUMMON_TANARRI                    304
#define SPELLABILITY_TRUMPET_BLAST                     305
#define SPELLABILITY_TYRANT_FOG_MIST                   306
#define SPELLABILITY_BARBARIAN_RAGE                    307
#define SPELLABILITY_TURN_UNDEAD                       308
#define SPELLABILITY_WHOLENESS_OF_BODY                 309
#define SPELLABILITY_QUIVERING_PALM                    310
#define SPELLABILITY_EMPTY_BODY                        311
#define SPELLABILITY_DETECT_EVIL                       312
#define SPELLABILITY_LAY_ON_HANDS                      313
#define SPELLABILITY_AURA_OF_COURAGE                   314
#define SPELLABILITY_SMITE_EVIL                        315
#define SPELLABILITY_REMOVE_DISEASE                    316
#define SPELLABILITY_SUMMON_ANIMAL_COMPANION           317
#define SPELLABILITY_SUMMON_FAMILIAR                   318
#define SPELLABILITY_ELEMENTAL_SHAPE                   319
#define SPELLABILITY_WILD_SHAPE                        320
#define SPELL_SHADES_SUMMON_SHADOW                     324
#define SPELL_SHADES_CONE_OF_COLD                      340
#define SPELL_SHADES_FIREBALL                          341
#define SPELL_SHADES_STONESKIN                         342
#define SPELL_SHADES_WALL_OF_FIRE                      343
#define SPELL_SHADOW_CONJURATION_SUMMON_SHADOW         344
#define SPELL_SHADOW_CONJURATION_DARKNESS              345
#define SPELL_SHADOW_CONJURATION_INIVSIBILITY          346
#define SPELL_SHADOW_CONJURATION_MAGE_ARMOR            347
#define SPELL_SHADOW_CONJURATION_MAGIC_MISSILE         348
#define SPELL_GREATER_SHADOW_CONJURATION_SUMMON_SHADOW 349
#define SPELL_GREATER_SHADOW_CONJURATION_ACID_ARROW    350
#define SPELL_GREATER_SHADOW_CONJURATION_MIRROR_IMAGE  351
#define SPELL_GREATER_SHADOW_CONJURATION_WEB           352
#define SPELL_GREATER_SHADOW_CONJURATION_MINOR_GLOBE   353
#define SPELL_EAGLE_SPLEDOR                            354
#define SPELL_OWLS_WISDOM                              355
#define SPELL_FOXS_CUNNING                             356
#define SPELL_GREATER_EAGLE_SPLENDOR                   357
#define SPELL_GREATER_OWLS_WISDOM                      358
#define SPELL_GREATER_FOXS_CUNNING                     359
#define SPELL_GREATER_BULLS_STRENGTH                   360
#define SPELL_GREATER_CATS_GRACE                       361
#define SPELL_GREATER_ENDURANCE                        362
#define SPELL_AWAKEN                                   363
#define SPELL_CREEPING_DOOM                            364
#define SPELL_DARKVISION                               365
#define SPELL_DESTRUCTION                              366
#define SPELL_HORRID_WILTING                           367
#define SPELL_ICE_STORM                                368
#define SPELL_ENERGY_BUFFER                            369
#define SPELL_NEGATIVE_ENERGY_BURST                    370
#define SPELL_NEGATIVE_ENERGY_RAY                      371
#define SPELL_AURA_OF_VITALITY                         372
#define SPELL_WAR_CRY                                  373
#define SPELL_REGENERATE                               374
#define SPELL_EVARDS_BLACK_TENTACLES                   375
#define SPELL_LEGEND_LORE                              376
#define SPELL_FIND_TRAPS                               377
#define SPELLABILITY_SUMMON_MEPHIT                     378
#define SPELLABILITY_SUMMON_CELESTIAL                  379
#define SPELLABILITY_BATTLE_MASTERY                    380
#define SPELLABILITY_DIVINE_STRENGTH                   381
#define SPELLABILITY_DIVINE_PROTECTION                 382
#define SPELLABILITY_NEGATIVE_PLANE_AVATAR             383
#define SPELLABILITY_DIVINE_TRICKERY                   384
#define SPELLABILITY_ROGUES_CUNNING                    385
#define SPELLABILITY_ACTIVATE_ITEM                     386
#define SPELLABILITY_DRAGON_FEAR                       412
#define SPELL_DIVINE_FAVOR                             414
#define SPELL_TRUE_STRIKE                              415
#define SPELL_FLARE                                    416
#define SPELL_SHIELD                                   417
#define SPELL_ENTROPIC_SHIELD                          418
#define SPELL_CONTINUAL_FLAME                          419
#define SPELL_ONE_WITH_THE_LAND                        420
#define SPELL_CAMOFLAGE                                421
#define SPELL_BLOOD_FRENZY                             422
#define SPELL_BOMBARDMENT                              423
#define SPELL_ACID_SPLASH                              424
#define SPELL_QUILLFIRE                                425
#define SPELL_EARTHQUAKE                               426
#define SPELL_SUNBURST                                 427
#define SPELL_ACTIVATE_ITEM_SELF2                      428
#define SPELL_AURAOFGLORY                              429
#define SPELL_BANISHMENT                               430
#define SPELL_INFLICT_MINOR_WOUNDS                     431
#define SPELL_INFLICT_LIGHT_WOUNDS                     432
#define SPELL_INFLICT_MODERATE_WOUNDS                  433
#define SPELL_INFLICT_SERIOUS_WOUNDS                   434
#define SPELL_INFLICT_CRITICAL_WOUNDS                  435
#define SPELL_BALAGARNSIRONHORN                        436
#define SPELL_DROWN                                    437
#define SPELL_OWLS_INSIGHT                             438
#define SPELL_ELECTRIC_JOLT                            439
#define SPELL_FIREBRAND                                440
#define SPELL_WOUNDING_WHISPERS                        441
#define SPELL_AMPLIFY                                  442
#define SPELL_ETHEREALNESS                             443
#define SPELL_UNDEATHS_ETERNAL_FOE                     444
#define SPELL_DIRGE                                    445
#define SPELL_INFERNO                                  446
#define SPELL_ISAACS_LESSER_MISSILE_STORM              447
#define SPELL_ISAACS_GREATER_MISSILE_STORM             448
#define SPELL_BANE                                     449
#define SPELL_SHIELD_OF_FAITH                          450
#define SPELL_PLANAR_ALLY                              451
#define SPELL_MAGIC_FANG                               452
#define SPELL_GREATER_MAGIC_FANG                       453
#define SPELL_SPIKE_GROWTH                             454
#define SPELL_MASS_CAMOFLAGE                           455
#define SPELL_EXPEDITIOUS_RETREAT                      456
#define SPELL_TASHAS_HIDEOUS_LAUGHTER                  457
#define SPELL_DISPLACEMENT                             458
#define SPELL_BIGBYS_INTERPOSING_HAND                  459
#define SPELL_BIGBYS_FORCEFUL_HAND                     460
#define SPELL_BIGBYS_GRASPING_HAND                     461
#define SPELL_BIGBYS_CLENCHED_FIST                     462
#define SPELL_BIGBYS_CRUSHING_HAND                     463
#define SPELL_GRENADE_FIRE                             464
#define SPELL_GRENADE_TANGLE                           465
#define SPELL_GRENADE_HOLY                             466
#define SPELL_GRENADE_CHOKING                          467
#define SPELL_GRENADE_THUNDERSTONE                     468
#define SPELL_GRENADE_ACID                             469
#define SPELL_GRENADE_CHICKEN                          470
#define SPELL_GRENADE_CALTROPS                         471
#define SPELL_ACTIVATE_ITEM_PORTAL                     472
#define SPELL_DIVINE_MIGHT                             473
#define SPELL_DIVINE_SHIELD                            474
#define SPELL_SHADOW_DAZE                              475
#define SPELL_SUMMON_SHADOW                            476
#define SPELL_SHADOW_EVADE                             477
#define SPELL_TYMORAS_SMILE                            478
#define SPELL_CRAFT_HARPER_ITEM                        479
#define SPELL_FLESH_TO_STONE                           485
#define SPELL_STONE_TO_FLESH                           486
#define SPELL_TRAP_ARROW                               487
#define SPELL_TRAP_BOLT                                488
#define SPELL_TRAP_DART                                493
#define SPELL_TRAP_SHURIKEN                            494
#define SPELLABILITY_BREATH_PETRIFY                    495
#define SPELLABILITY_TOUCH_PETRIFY                     496
#define SPELLABILITY_GAZE_PETRIFY                      497
#define SPELLABILITY_MANTICORE_SPIKES                  498
#define SPELL_ROD_OF_WONDER                            499
#define SPELL_DECK_OF_MANY_THINGS                      500
#define SPELL_ELEMENTAL_SUMMONING_ITEM                 502
#define SPELL_DECK_AVATAR                              503
#define SPELL_DECK_GEMSPRAY                            504
#define SPELL_DECK_BUTTERFLYSPRAY                      505
#define SPELL_HEALINGKIT                               506
#define SPELL_POWERSTONE                               507
#define SPELL_SPELLSTAFF                               508
#define SPELL_CHARGER                                  500
#define SPELL_DECHARGER                                510
#define SPELL_KOBOLD_JUMP                              511
#define SPELL_CRUMBLE                                  512
#define SPELL_INFESTATION_OF_MAGGOTS                   513
#define SPELL_HEALING_STING                            514
#define SPELL_GREAT_THUNDERCLAP                        515
#define SPELL_BALL_LIGHTNING                           516
#define SPELL_BATTLETIDE                               517
#define SPELL_COMBUST                                  518
#define SPELL_DEATH_ARMOR                              519
#define SPELL_GEDLEES_ELECTRIC_LOOP                    520
#define SPELL_HORIZIKAULS_BOOM                         521
#define SPELL_IRONGUTS                                 522
#define SPELL_MESTILS_ACID_BREATH                      523
#define SPELL_MESTILS_ACID_SHEATH                      524
#define SPELL_MONSTROUS_REGENERATION                   525
#define SPELL_SCINTILLATING_SPHERE                     526
#define SPELL_STONE_BONES                              527
#define SPELL_UNDEATH_TO_DEATH                         528
#define SPELL_VINE_MINE                                529
#define SPELL_VINE_MINE_ENTANGLE                       530
#define SPELL_VINE_MINE_HAMPER_MOVEMENT                531
#define SPELL_VINE_MINE_CAMOUFLAGE                     532
#define SPELL_BLACK_BLADE_OF_DISASTER                  533
#define SPELL_SHELGARNS_PERSISTENT_BLADE               534
#define SPELL_BLADE_THIRST                             535
#define SPELL_DEAFENING_CLANG                          536
#define SPELL_CLOUD_OF_BEWILDERMENT                    569
#define SPELL_KEEN_EDGE                                539
#define SPELL_BLACKSTAFF                               541
#define SPELL_FLAME_WEAPON                             542
#define SPELL_ICE_DAGGER                               543
#define SPELL_MAGIC_WEAPON                             544
#define SPELL_GREATER_MAGIC_WEAPON                     545
#define SPELL_STONEHOLD                                547
#define SPELL_DARKFIRE                                 548
#define SPELL_GLYPH_OF_WARDING                         549
#define SPELLABILITY_MINDBLAST                         551
#define SPELLABILITY_CHARMMONSTER                      552
#define SPELL_IOUN_STONE_DUSTY_ROSE                    554
#define SPELL_IOUN_STONE_PALE_BLUE                     555
#define SPELL_IOUN_STONE_SCARLET_BLUE                  556
#define SPELL_IOUN_STONE_BLUE                          557
#define SPELL_IOUN_STONE_DEEP_RED                      558
#define SPELL_IOUN_STONE_PINK                          559
#define SPELL_IOUN_STONE_PINK_GREEN                    560
#define SPELLABILITY_WHIRLWIND                         561
#define SPELLABILITY_COMMAND_THE_HORDE                 571
#define SPELLABILITY_AA_IMBUE_ARROW                    600
#define SPELLABILITY_AA_SEEKER_ARROW_1                 601
#define SPELLABILITY_AA_SEEKER_ARROW_2                 602
#define SPELLABILITY_AA_HAIL_OF_ARROWS                 603
#define SPELLABILITY_AA_ARROW_OF_DEATH                 604
#define SPELLABILITY_AS_GHOSTLY_VISAGE                 605
#define SPELLABILITY_AS_DARKNESS                       606
#define SPELLABILITY_AS_INVISIBILITY                   607
#define SPELLABILITY_AS_IMPROVED_INVISIBLITY           608
#define SPELLABILITY_BG_CREATEDEAD                     609
#define SPELLABILITY_BG_FIENDISH_SERVANT               610
#define SPELLABILITY_BG_INFLICT_SERIOUS_WOUNDS         611
#define SPELLABILITY_BG_INFLICT_CRITICAL_WOUNDS        612
#define SPELLABILITY_BG_CONTAGION                      613
#define SPELLABILITY_BG_BULLS_STRENGTH                 614
#define SPELL_FLYING_DEBRIS                            620
#define SPELLABILITY_DC_DIVINE_WRATH                   622
#define SPELLABILITY_PM_ANIMATE_DEAD                   623
#define SPELLABILITY_PM_SUMMON_UNDEAD                  624
#define SPELLABILITY_PM_UNDEAD_GRAFT_1                 625
#define SPELLABILITY_PM_UNDEAD_GRAFT_2                 626
#define SPELLABILITY_PM_SUMMON_GREATER_UNDEAD          627
#define SPELLABILITY_PM_DEATHLESS_MASTER_TOUCH         628
#define SPELL_EPIC_HELLBALL                            636
#define SPELL_EPIC_MUMMY_DUST                          637
#define SPELL_EPIC_DRAGON_KNIGHT                       638
#define SPELL_EPIC_MAGE_ARMOR                          639
#define SPELL_EPIC_RUIN                                640
#define SPELLABILITY_DW_DEFENSIVE_STANCE               641
#define SPELLABILITY_EPIC_MIGHTY_RAGE                  642
#define SPELLABILITY_EPIC_CURSE_SONG                   644
#define SPELLABILITY_EPIC_IMPROVED_WHIRLWIND           645
#define SPELLABILITY_EPIC_SHAPE_DRAGONKIN              646
#define SPELLABILITY_EPIC_SHAPE_DRAGON                 647
#define SPELL_CRAFT_DYE_CLOTHCOLOR_1                   648
#define SPELL_CRAFT_DYE_CLOTHCOLOR_2                   649
#define SPELL_CRAFT_DYE_LEATHERCOLOR_1                 650
#define SPELL_CRAFT_DYE_LEATHERCOLOR_2                 651
#define SPELL_CRAFT_DYE_METALCOLOR_1                   652
#define SPELL_CRAFT_DYE_METALCOLOR_2                   653
#define SPELL_CRAFT_ADD_ITEM_PROPERTY                  654
#define SPELL_CRAFT_POISON_WEAPON_OR_AMMO              655
#define SPELL_CRAFT_CRAFT_WEAPON_SKILL                 656
#define SPELL_CRAFT_CRAFT_ARMOR_SKILL                  657
#define SPELLABILITY_DRAGON_BREATH_NEGATIVE            698
#define SPELLABILITY_SEAHAG_EVILEYE                    803
#define SPELLABILITY_AURA_HORRIFICAPPEARANCE           804
#define SPELLABILITY_TROGLODYTE_STENCH                 805
#define SPELL_HORSE_MENU                               812
#define SPELL_HORSE_MOUNT                              813
#define SPELL_HORSE_DISMOUNT                           814
#define SPELL_HORSE_PARTY_MOUNT                        815
#define SPELL_HORSE_PARTY_DISMOUNT                     816
#define SPELL_HORSE_ASSIGN_MOUNT                       817
#define SPELL_PALADIN_SUMMON_MOUNT                     818

#define USE_CREATURE_LEVEL 0

#endif /* _NX_NWN_CONST_SPELLS_H_ */

/* vim: set sw=4: */
