/*
 *  (c) 2013 jmd (jmd2028 at gmail dot com)
 *
 *  This program is free software you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 *  $Id$
 *  $HeadURL$
 *
 */

#ifndef _NX_NWN_CONST_ITEMPROP_H_
#define _NX_NWN_CONST_ITEMPROP_H_

#define ITEM_PROPERTY_ABILITY_BONUS                             0
#define ITEM_PROPERTY_AC_BONUS                                  1
#define ITEM_PROPERTY_AC_BONUS_VS_ALIGNMENT_GROUP               2
#define ITEM_PROPERTY_AC_BONUS_VS_DAMAGE_TYPE                   3
#define ITEM_PROPERTY_AC_BONUS_VS_RACIAL_GROUP                  4
#define ITEM_PROPERTY_AC_BONUS_VS_SPECIFIC_ALIGNMENT            5
#define ITEM_PROPERTY_ENHANCEMENT_BONUS                         6
#define ITEM_PROPERTY_ENHANCEMENT_BONUS_VS_ALIGNMENT_GROUP      7
#define ITEM_PROPERTY_ENHANCEMENT_BONUS_VS_RACIAL_GROUP         8
#define ITEM_PROPERTY_ENHANCEMENT_BONUS_VS_SPECIFIC_ALIGNEMENT  9
#define ITEM_PROPERTY_DECREASED_ENHANCEMENT_MODIFIER            10
#define ITEM_PROPERTY_BASE_ITEM_WEIGHT_REDUCTION                11
#define ITEM_PROPERTY_BONUS_FEAT                                12
#define ITEM_PROPERTY_BONUS_SPELL_SLOT_OF_LEVEL_N               13
#define ITEM_PROPERTY_CAST_SPELL                                15
#define ITEM_PROPERTY_DAMAGE_BONUS                              16
#define ITEM_PROPERTY_DAMAGE_BONUS_VS_ALIGNMENT_GROUP           17
#define ITEM_PROPERTY_DAMAGE_BONUS_VS_RACIAL_GROUP              18
#define ITEM_PROPERTY_DAMAGE_BONUS_VS_SPECIFIC_ALIGNMENT        19
#define ITEM_PROPERTY_IMMUNITY_DAMAGE_TYPE                      20
#define ITEM_PROPERTY_DECREASED_DAMAGE                          21
#define ITEM_PROPERTY_DAMAGE_REDUCTION                          22
#define ITEM_PROPERTY_DAMAGE_RESISTANCE                         23
#define ITEM_PROPERTY_DAMAGE_VULNERABILITY                      24
#define ITEM_PROPERTY_DARKVISION                                26
#define ITEM_PROPERTY_DECREASED_ABILITY_SCORE                   27
#define ITEM_PROPERTY_DECREASED_AC                              28
#define ITEM_PROPERTY_DECREASED_SKILL_MODIFIER                  29
#define ITEM_PROPERTY_ENHANCED_CONTAINER_REDUCED_WEIGHT         32
#define ITEM_PROPERTY_EXTRA_MELEE_DAMAGE_TYPE                   33
#define ITEM_PROPERTY_EXTRA_RANGED_DAMAGE_TYPE                  34
#define ITEM_PROPERTY_HASTE                                     35
#define ITEM_PROPERTY_HOLY_AVENGER                              36
#define ITEM_PROPERTY_IMMUNITY_MISCELLANEOUS                    37
#define ITEM_PROPERTY_IMPROVED_EVASION                          38
#define ITEM_PROPERTY_SPELL_RESISTANCE                          39
#define ITEM_PROPERTY_SAVING_THROW_BONUS                        40
#define ITEM_PROPERTY_SAVING_THROW_BONUS_SPECIFIC               41
#define ITEM_PROPERTY_KEEN                                      43
#define ITEM_PROPERTY_LIGHT                                     44
#define ITEM_PROPERTY_MIGHTY                                    45
#define ITEM_PROPERTY_MIND_BLANK                                46
#define ITEM_PROPERTY_NO_DAMAGE                                 47
#define ITEM_PROPERTY_ON_HIT_PROPERTIES                         48
#define ITEM_PROPERTY_DECREASED_SAVING_THROWS                   49
#define ITEM_PROPERTY_DECREASED_SAVING_THROWS_SPECIFIC          50
#define ITEM_PROPERTY_REGENERATION                              51
#define ITEM_PROPERTY_SKILL_BONUS                               52
#define ITEM_PROPERTY_IMMUNITY_SPECIFIC_SPELL                   53
#define ITEM_PROPERTY_IMMUNITY_SPELL_SCHOOL                     54
#define ITEM_PROPERTY_THIEVES_TOOLS                             55
#define ITEM_PROPERTY_ATTACK_BONUS                              56
#define ITEM_PROPERTY_ATTACK_BONUS_VS_ALIGNMENT_GROUP           57
#define ITEM_PROPERTY_ATTACK_BONUS_VS_RACIAL_GROUP              58
#define ITEM_PROPERTY_ATTACK_BONUS_VS_SPECIFIC_ALIGNMENT        59
#define ITEM_PROPERTY_DECREASED_ATTACK_MODIFIER                 60
#define ITEM_PROPERTY_UNLIMITED_AMMUNITION                      61
#define ITEM_PROPERTY_USE_LIMITATION_ALIGNMENT_GROUP            62
#define ITEM_PROPERTY_USE_LIMITATION_CLASS                      63
#define ITEM_PROPERTY_USE_LIMITATION_RACIAL_TYPE                64
#define ITEM_PROPERTY_USE_LIMITATION_SPECIFIC_ALIGNMENT         65
#define ITEM_PROPERTY_USE_LIMITATION_TILESET                    66
#define ITEM_PROPERTY_REGENERATION_VAMPIRIC                     67
#define ITEM_PROPERTY_TRAP                                      70
#define ITEM_PROPERTY_TRUE_SEEING                               71
#define ITEM_PROPERTY_ON_MONSTER_HIT                            72
#define ITEM_PROPERTY_TURN_RESISTANCE                           73
#define ITEM_PROPERTY_MASSIVE_CRITICALS                         74
#define ITEM_PROPERTY_FREEDOM_OF_MOVEMENT                       75
#define ITEM_PROPERTY_MONSTER_DAMAGE                            77
#define ITEM_PROPERTY_IMMUNITY_SPELLS_BY_LEVEL                  78
#define ITEM_PROPERTY_SPECIAL_WALK                              79
#define ITEM_PROPERTY_HEALERS_KIT                               80
#define ITEM_PROPERTY_WEIGHT_INCREASE                           81
#define ITEM_PROPERTY_ONHITCASTSPELL                            82
#define ITEM_PROPERTY_VISUALEFFECT                              83
#define ITEM_PROPERTY_ARCANE_SPELL_FAILURE                      84
#define ITEM_PROPERTY_MATERIAL                                  85
#define ITEM_PROPERTY_QUALITY                                   86
#define ITEM_PROPERTY_ADDITIONAL                                87

// The following is all the item property constants...
#define IP_CONST_ABILITY_STR                         0
#define IP_CONST_ABILITY_DEX                         1
#define IP_CONST_ABILITY_CON                         2
#define IP_CONST_ABILITY_INT                         3
#define IP_CONST_ABILITY_WIS                         4
#define IP_CONST_ABILITY_CHA                         5
#define IP_CONST_ACMODIFIERTYPE_DODGE                0
#define IP_CONST_ACMODIFIERTYPE_NATURAL              1
#define IP_CONST_ACMODIFIERTYPE_ARMOR                2
#define IP_CONST_ACMODIFIERTYPE_SHIELD               3
#define IP_CONST_ACMODIFIERTYPE_DEFLECTION           4
#define IP_CONST_ADDITIONAL_UNKNOWN                  0
#define IP_CONST_ADDITIONAL_CURSED                   1
#define IP_CONST_ALIGNMENTGROUP_ALL                  0
#define IP_CONST_ALIGNMENTGROUP_NEUTRAL              1
#define IP_CONST_ALIGNMENTGROUP_LAWFUL               2
#define IP_CONST_ALIGNMENTGROUP_CHAOTIC              3
#define IP_CONST_ALIGNMENTGROUP_GOOD                 4
#define IP_CONST_ALIGNMENTGROUP_EVIL                 5
#define IP_CONST_ALIGNMENT_LG                        0
#define IP_CONST_ALIGNMENT_LN                        1
#define IP_CONST_ALIGNMENT_LE                        2
#define IP_CONST_ALIGNMENT_NG                        3
#define IP_CONST_ALIGNMENT_TN                        4
#define IP_CONST_ALIGNMENT_NE                        5
#define IP_CONST_ALIGNMENT_CG                        6
#define IP_CONST_ALIGNMENT_CN                        7
#define IP_CONST_ALIGNMENT_CE                        8
#define IP_CONST_RACIALTYPE_DWARF                    0
#define IP_CONST_RACIALTYPE_ELF                      1
#define IP_CONST_RACIALTYPE_GNOME                    2
#define IP_CONST_RACIALTYPE_HALFLING                 3
#define IP_CONST_RACIALTYPE_HALFELF                  4
#define IP_CONST_RACIALTYPE_HALFORC                  5
#define IP_CONST_RACIALTYPE_HUMAN                    6
#define IP_CONST_RACIALTYPE_ABERRATION               7
#define IP_CONST_RACIALTYPE_ANIMAL                   8
#define IP_CONST_RACIALTYPE_BEAST                    9
#define IP_CONST_RACIALTYPE_CONSTRUCT                10
#define IP_CONST_RACIALTYPE_DRAGON                   11
#define IP_CONST_RACIALTYPE_HUMANOID_GOBLINOID       12
#define IP_CONST_RACIALTYPE_HUMANOID_MONSTROUS       13
#define IP_CONST_RACIALTYPE_HUMANOID_ORC             14
#define IP_CONST_RACIALTYPE_HUMANOID_REPTILIAN       15
#define IP_CONST_RACIALTYPE_ELEMENTAL                16
#define IP_CONST_RACIALTYPE_FEY                      17
#define IP_CONST_RACIALTYPE_GIANT                    18
#define IP_CONST_RACIALTYPE_MAGICAL_BEAST            19
#define IP_CONST_RACIALTYPE_OUTSIDER                 20
#define IP_CONST_RACIALTYPE_SHAPECHANGER             23
#define IP_CONST_RACIALTYPE_UNDEAD                   24
#define IP_CONST_RACIALTYPE_VERMIN                   25
#define IP_CONST_UNLIMITEDAMMO_BASIC                 1
#define IP_CONST_UNLIMITEDAMMO_1D6FIRE               2
#define IP_CONST_UNLIMITEDAMMO_1D6COLD               3
#define IP_CONST_UNLIMITEDAMMO_1D6LIGHT              4
#define IP_CONST_UNLIMITEDAMMO_PLUS1                 11
#define IP_CONST_UNLIMITEDAMMO_PLUS2                 12
#define IP_CONST_UNLIMITEDAMMO_PLUS3                 13
#define IP_CONST_UNLIMITEDAMMO_PLUS4                 14
#define IP_CONST_UNLIMITEDAMMO_PLUS5                 15
#define IP_CONST_AMMOTYPE_ARROW                      0
#define IP_CONST_AMMOTYPE_BOLT                       1
#define IP_CONST_AMMOTYPE_BULLET                     2
#define IP_CONST_CASTSPELL_NUMUSES_SINGLE_USE            1
#define IP_CONST_CASTSPELL_NUMUSES_5_CHARGES_PER_USE     2
#define IP_CONST_CASTSPELL_NUMUSES_4_CHARGES_PER_USE     3
#define IP_CONST_CASTSPELL_NUMUSES_3_CHARGES_PER_USE     4
#define IP_CONST_CASTSPELL_NUMUSES_2_CHARGES_PER_USE     5
#define IP_CONST_CASTSPELL_NUMUSES_1_CHARGE_PER_USE      6
#define IP_CONST_CASTSPELL_NUMUSES_0_CHARGES_PER_USE     7
#define IP_CONST_CASTSPELL_NUMUSES_1_USE_PER_DAY         8
#define IP_CONST_CASTSPELL_NUMUSES_2_USES_PER_DAY        9
#define IP_CONST_CASTSPELL_NUMUSES_3_USES_PER_DAY        10
#define IP_CONST_CASTSPELL_NUMUSES_4_USES_PER_DAY        11
#define IP_CONST_CASTSPELL_NUMUSES_5_USES_PER_DAY        12
#define IP_CONST_CASTSPELL_NUMUSES_UNLIMITED_USE         13
#define IP_CONST_DAMAGEBONUS_1                       1
#define IP_CONST_DAMAGEBONUS_2                       2
#define IP_CONST_DAMAGEBONUS_3                       3
#define IP_CONST_DAMAGEBONUS_4                       4
#define IP_CONST_DAMAGEBONUS_5                       5
#define IP_CONST_DAMAGEBONUS_1d4                     6
#define IP_CONST_DAMAGEBONUS_1d6                     7
#define IP_CONST_DAMAGEBONUS_1d8                     8
#define IP_CONST_DAMAGEBONUS_1d10                    9
#define IP_CONST_DAMAGEBONUS_2d6                     10
#define IP_CONST_DAMAGEBONUS_2d8                 11
#define IP_CONST_DAMAGEBONUS_2d4                 12
#define IP_CONST_DAMAGEBONUS_2d10                13
#define IP_CONST_DAMAGEBONUS_1d12                14
#define IP_CONST_DAMAGEBONUS_2d12                15
#define IP_CONST_DAMAGEBONUS_6                   16
#define IP_CONST_DAMAGEBONUS_7                   17
#define IP_CONST_DAMAGEBONUS_8                   18
#define IP_CONST_DAMAGEBONUS_9                   19
#define IP_CONST_DAMAGEBONUS_10                  20
#define IP_CONST_DAMAGETYPE_BLUDGEONING              0
#define IP_CONST_DAMAGETYPE_PIERCING                 1
#define IP_CONST_DAMAGETYPE_SLASHING                 2
#define IP_CONST_DAMAGETYPE_SUBDUAL                  3
#define IP_CONST_DAMAGETYPE_PHYSICAL                 4
#define IP_CONST_DAMAGETYPE_MAGICAL                  5
#define IP_CONST_DAMAGETYPE_ACID                     6
#define IP_CONST_DAMAGETYPE_COLD                     7
#define IP_CONST_DAMAGETYPE_DIVINE                   8
#define IP_CONST_DAMAGETYPE_ELECTRICAL               9
#define IP_CONST_DAMAGETYPE_FIRE                     10
#define IP_CONST_DAMAGETYPE_NEGATIVE                 11
#define IP_CONST_DAMAGETYPE_POSITIVE                 12
#define IP_CONST_DAMAGETYPE_SONIC                    13
#define IP_CONST_DAMAGEIMMUNITY_5_PERCENT            1
#define IP_CONST_DAMAGEIMMUNITY_10_PERCENT           2
#define IP_CONST_DAMAGEIMMUNITY_25_PERCENT           3
#define IP_CONST_DAMAGEIMMUNITY_50_PERCENT           4
#define IP_CONST_DAMAGEIMMUNITY_75_PERCENT           5
#define IP_CONST_DAMAGEIMMUNITY_90_PERCENT           6
#define IP_CONST_DAMAGEIMMUNITY_100_PERCENT          7
#define IP_CONST_DAMAGEVULNERABILITY_5_PERCENT       1
#define IP_CONST_DAMAGEVULNERABILITY_10_PERCENT      2
#define IP_CONST_DAMAGEVULNERABILITY_25_PERCENT      3
#define IP_CONST_DAMAGEVULNERABILITY_50_PERCENT      4
#define IP_CONST_DAMAGEVULNERABILITY_75_PERCENT      5
#define IP_CONST_DAMAGEVULNERABILITY_90_PERCENT      6
#define IP_CONST_DAMAGEVULNERABILITY_100_PERCENT     7
#define IP_CONST_FEAT_ALERTNESS                      0
#define IP_CONST_FEAT_AMBIDEXTROUS                   1
#define IP_CONST_FEAT_CLEAVE                         2
#define IP_CONST_FEAT_COMBAT_CASTING                 3
#define IP_CONST_FEAT_DODGE                          4
#define IP_CONST_FEAT_EXTRA_TURNING                  5
#define IP_CONST_FEAT_KNOCKDOWN                      6
#define IP_CONST_FEAT_POINTBLANK                     7
#define IP_CONST_FEAT_SPELLFOCUSABJ                  8
#define IP_CONST_FEAT_SPELLFOCUSCON                  9
#define IP_CONST_FEAT_SPELLFOCUSDIV                  10
#define IP_CONST_FEAT_SPELLFOCUSENC                  11
#define IP_CONST_FEAT_SPELLFOCUSEVO                  12
#define IP_CONST_FEAT_SPELLFOCUSILL                  13
#define IP_CONST_FEAT_SPELLFOCUSNEC                  14
#define IP_CONST_FEAT_SPELLPENETRATION               15
#define IP_CONST_FEAT_POWERATTACK                    16
#define IP_CONST_FEAT_TWO_WEAPON_FIGHTING            17
#define IP_CONST_FEAT_WEAPSPEUNARM                   18
#define IP_CONST_FEAT_WEAPFINESSE                    19
#define IP_CONST_FEAT_IMPCRITUNARM                   20
#define IP_CONST_FEAT_WEAPON_PROF_EXOTIC             21
#define IP_CONST_FEAT_WEAPON_PROF_MARTIAL            22
#define IP_CONST_FEAT_WEAPON_PROF_SIMPLE             23
#define IP_CONST_FEAT_ARMOR_PROF_HEAVY               24
#define IP_CONST_FEAT_ARMOR_PROF_LIGHT               25
#define IP_CONST_FEAT_ARMOR_PROF_MEDIUM              26
#define IP_CONST_FEAT_MOBILITY                       27
#define IP_CONST_FEAT_DISARM                         28
#define IP_CONST_FEAT_WHIRLWIND                      29
#define IP_CONST_FEAT_RAPID_SHOT                     30
#define IP_CONST_FEAT_HIDE_IN_PLAIN_SIGHT            31
#define IP_CONST_FEAT_SNEAK_ATTACK_1D6               32
#define IP_CONST_FEAT_SNEAK_ATTACK_2D6               33
#define IP_CONST_FEAT_SNEAK_ATTACK_3D6               34
#define IP_CONST_FEAT_SHIELD_PROFICIENCY             35
#define IP_CONST_FEAT_USE_POISON                     36
#define IP_CONST_FEAT_DISARM_WHIP                    37
#define IP_CONST_FEAT_WEAPON_PROF_CREATURE           38
#define IP_CONST_FEAT_SNEAK_ATTACK_5D6               39
#define IP_CONST_FEAT_PLAYER_TOOL_01                 53
#define IP_CONST_FEAT_PLAYER_TOOL_02                 54
#define IP_CONST_FEAT_PLAYER_TOOL_03                 55
#define IP_CONST_FEAT_PLAYER_TOOL_04                 56
#define IP_CONST_FEAT_PLAYER_TOOL_05                 57
#define IP_CONST_FEAT_PLAYER_TOOL_06                 58
#define IP_CONST_FEAT_PLAYER_TOOL_07                 59
#define IP_CONST_FEAT_PLAYER_TOOL_08                 60
#define IP_CONST_FEAT_PLAYER_TOOL_09                 61
#define IP_CONST_FEAT_PLAYER_TOOL_10                 62
#define IP_CONST_IMMUNITYMISC_BACKSTAB               0
#define IP_CONST_IMMUNITYMISC_LEVEL_ABIL_DRAIN       1
#define IP_CONST_IMMUNITYMISC_MINDSPELLS             2
#define IP_CONST_IMMUNITYMISC_POISON                 3
#define IP_CONST_IMMUNITYMISC_DISEASE                4
#define IP_CONST_IMMUNITYMISC_FEAR                   5
#define IP_CONST_IMMUNITYMISC_KNOCKDOWN              6
#define IP_CONST_IMMUNITYMISC_PARALYSIS              7
#define IP_CONST_IMMUNITYMISC_CRITICAL_HITS          8
#define IP_CONST_IMMUNITYMISC_DEATH_MAGIC            9
#define IP_CONST_LIGHTBRIGHTNESS_DIM                 1
#define IP_CONST_LIGHTBRIGHTNESS_LOW                 2
#define IP_CONST_LIGHTBRIGHTNESS_NORMAL              3
#define IP_CONST_LIGHTBRIGHTNESS_BRIGHT              4
#define IP_CONST_LIGHTCOLOR_BLUE                     0
#define IP_CONST_LIGHTCOLOR_YELLOW                   1
#define IP_CONST_LIGHTCOLOR_PURPLE                   2
#define IP_CONST_LIGHTCOLOR_RED                      3
#define IP_CONST_LIGHTCOLOR_GREEN                    4
#define IP_CONST_LIGHTCOLOR_ORANGE                   5
#define IP_CONST_LIGHTCOLOR_WHITE                    6
#define IP_CONST_MONSTERDAMAGE_1d2                   1
#define IP_CONST_MONSTERDAMAGE_1d3                   2
#define IP_CONST_MONSTERDAMAGE_1d4                   3
#define IP_CONST_MONSTERDAMAGE_2d4                   4
#define IP_CONST_MONSTERDAMAGE_3d4                   5
#define IP_CONST_MONSTERDAMAGE_4d4                   6
#define IP_CONST_MONSTERDAMAGE_5d4                   7
#define IP_CONST_MONSTERDAMAGE_1d6                   8
#define IP_CONST_MONSTERDAMAGE_2d6                   9
#define IP_CONST_MONSTERDAMAGE_3d6                   10
#define IP_CONST_MONSTERDAMAGE_4d6                   11
#define IP_CONST_MONSTERDAMAGE_5d6                   12
#define IP_CONST_MONSTERDAMAGE_6d6                   13
#define IP_CONST_MONSTERDAMAGE_7d6                   14
#define IP_CONST_MONSTERDAMAGE_8d6                   15
#define IP_CONST_MONSTERDAMAGE_9d6                   16
#define IP_CONST_MONSTERDAMAGE_10d6                  17
#define IP_CONST_MONSTERDAMAGE_1d8                   18
#define IP_CONST_MONSTERDAMAGE_2d8                   19
#define IP_CONST_MONSTERDAMAGE_3d8                   20
#define IP_CONST_MONSTERDAMAGE_4d8                   21
#define IP_CONST_MONSTERDAMAGE_5d8                   22
#define IP_CONST_MONSTERDAMAGE_6d8                   23
#define IP_CONST_MONSTERDAMAGE_7d8                   24
#define IP_CONST_MONSTERDAMAGE_8d8                   25
#define IP_CONST_MONSTERDAMAGE_9d8                   26
#define IP_CONST_MONSTERDAMAGE_10d8                  27
#define IP_CONST_MONSTERDAMAGE_1d10                  28
#define IP_CONST_MONSTERDAMAGE_2d10                  29
#define IP_CONST_MONSTERDAMAGE_3d10                  30
#define IP_CONST_MONSTERDAMAGE_4d10                  31
#define IP_CONST_MONSTERDAMAGE_5d10                  32
#define IP_CONST_MONSTERDAMAGE_6d10                  33
#define IP_CONST_MONSTERDAMAGE_7d10                  34
#define IP_CONST_MONSTERDAMAGE_8d10                  35
#define IP_CONST_MONSTERDAMAGE_9d10                  36
#define IP_CONST_MONSTERDAMAGE_10d10                 37
#define IP_CONST_MONSTERDAMAGE_1d12                  38
#define IP_CONST_MONSTERDAMAGE_2d12                  39
#define IP_CONST_MONSTERDAMAGE_3d12                  40
#define IP_CONST_MONSTERDAMAGE_4d12                  41
#define IP_CONST_MONSTERDAMAGE_5d12                  42
#define IP_CONST_MONSTERDAMAGE_6d12                  43
#define IP_CONST_MONSTERDAMAGE_7d12                  44
#define IP_CONST_MONSTERDAMAGE_8d12                  45
#define IP_CONST_MONSTERDAMAGE_9d12                  46
#define IP_CONST_MONSTERDAMAGE_10d12                 47
#define IP_CONST_MONSTERDAMAGE_1d20                  48
#define IP_CONST_MONSTERDAMAGE_2d20                  49
#define IP_CONST_MONSTERDAMAGE_3d20                  50
#define IP_CONST_MONSTERDAMAGE_4d20                  51
#define IP_CONST_MONSTERDAMAGE_5d20                  52
#define IP_CONST_MONSTERDAMAGE_6d20                  53
#define IP_CONST_MONSTERDAMAGE_7d20                  54
#define IP_CONST_MONSTERDAMAGE_8d20                  55
#define IP_CONST_MONSTERDAMAGE_9d20                  56
#define IP_CONST_MONSTERDAMAGE_10d20                 57
#define IP_CONST_ONMONSTERHIT_ABILITYDRAIN           0
#define IP_CONST_ONMONSTERHIT_CONFUSION              1
#define IP_CONST_ONMONSTERHIT_DISEASE                2
#define IP_CONST_ONMONSTERHIT_DOOM                   3
#define IP_CONST_ONMONSTERHIT_FEAR                   4
#define IP_CONST_ONMONSTERHIT_LEVELDRAIN             5
#define IP_CONST_ONMONSTERHIT_POISON                 6
#define IP_CONST_ONMONSTERHIT_SLOW                   7
#define IP_CONST_ONMONSTERHIT_STUN                   8
#define IP_CONST_ONMONSTERHIT_WOUNDING               9
#define IP_CONST_ONHIT_SLEEP                         0
#define IP_CONST_ONHIT_STUN                          1
#define IP_CONST_ONHIT_HOLD                          2
#define IP_CONST_ONHIT_CONFUSION                     3
#define IP_CONST_ONHIT_DAZE                          5
#define IP_CONST_ONHIT_DOOM                          6
#define IP_CONST_ONHIT_FEAR                          7
#define IP_CONST_ONHIT_KNOCK                         8
#define IP_CONST_ONHIT_SLOW                          9
#define IP_CONST_ONHIT_LESSERDISPEL                  10
#define IP_CONST_ONHIT_DISPELMAGIC                   11
#define IP_CONST_ONHIT_GREATERDISPEL                 12
#define IP_CONST_ONHIT_MORDSDISJUNCTION              13
#define IP_CONST_ONHIT_SILENCE                       14
#define IP_CONST_ONHIT_DEAFNESS                      15
#define IP_CONST_ONHIT_BLINDNESS                     16
#define IP_CONST_ONHIT_LEVELDRAIN                    17
#define IP_CONST_ONHIT_ABILITYDRAIN                  18
#define IP_CONST_ONHIT_ITEMPOISON                    19
#define IP_CONST_ONHIT_DISEASE                       20
#define IP_CONST_ONHIT_SLAYRACE                      21
#define IP_CONST_ONHIT_SLAYALIGNMENTGROUP            22
#define IP_CONST_ONHIT_SLAYALIGNMENT                 23
#define IP_CONST_ONHIT_VORPAL                        24
#define IP_CONST_ONHIT_WOUNDING                      25
#define IP_CONST_ONHIT_SAVEDC_14                     0
#define IP_CONST_ONHIT_SAVEDC_16                     1
#define IP_CONST_ONHIT_SAVEDC_18                     2
#define IP_CONST_ONHIT_SAVEDC_20                     3
#define IP_CONST_ONHIT_SAVEDC_22                     4
#define IP_CONST_ONHIT_SAVEDC_24                     5
#define IP_CONST_ONHIT_SAVEDC_26                     6
#define IP_CONST_ONHIT_DURATION_5_PERCENT_5_ROUNDS   0
#define IP_CONST_ONHIT_DURATION_10_PERCENT_4_ROUNDS  1
#define IP_CONST_ONHIT_DURATION_25_PERCENT_3_ROUNDS  2
#define IP_CONST_ONHIT_DURATION_50_PERCENT_2_ROUNDS  3
#define IP_CONST_ONHIT_DURATION_75_PERCENT_1_ROUND   4

#define IP_CONST_ONHIT_CASTSPELL_ACID_FOG                            0
#define IP_CONST_ONHIT_CASTSPELL_BESTOW_CURSE                        1
#define IP_CONST_ONHIT_CASTSPELL_BLADE_BARRIER                       2
#define IP_CONST_ONHIT_CASTSPELL_BLINDNESS_AND_DEAFNESS              3
#define IP_CONST_ONHIT_CASTSPELL_CALL_LIGHTNING                      4
#define IP_CONST_ONHIT_CASTSPELL_CHAIN_LIGHTNING                     5
#define IP_CONST_ONHIT_CASTSPELL_CLOUDKILL                           6
#define IP_CONST_ONHIT_CASTSPELL_CONFUSION                           7
#define IP_CONST_ONHIT_CASTSPELL_CONTAGION                           8
#define IP_CONST_ONHIT_CASTSPELL_DARKNESS                            9
#define IP_CONST_ONHIT_CASTSPELL_DAZE                                10
#define IP_CONST_ONHIT_CASTSPELL_DELAYED_BLAST_FIREBALL              11
#define IP_CONST_ONHIT_CASTSPELL_DISMISSAL                           12
#define IP_CONST_ONHIT_CASTSPELL_DISPEL_MAGIC                        13
#define IP_CONST_ONHIT_CASTSPELL_DOOM                                14
#define IP_CONST_ONHIT_CASTSPELL_ENERGY_DRAIN                        15
#define IP_CONST_ONHIT_CASTSPELL_ENERVATION                          16
#define IP_CONST_ONHIT_CASTSPELL_ENTANGLE                            17
#define IP_CONST_ONHIT_CASTSPELL_FEAR                                18
#define IP_CONST_ONHIT_CASTSPELL_FEEBLEMIND                          19
#define IP_CONST_ONHIT_CASTSPELL_FIRE_STORM                          20
#define IP_CONST_ONHIT_CASTSPELL_FIREBALL                            21
#define IP_CONST_ONHIT_CASTSPELL_FLAME_LASH                          22
#define IP_CONST_ONHIT_CASTSPELL_FLAME_STRIKE                        23
#define IP_CONST_ONHIT_CASTSPELL_GHOUL_TOUCH                         24
#define IP_CONST_ONHIT_CASTSPELL_GREASE                              25
#define IP_CONST_ONHIT_CASTSPELL_GREATER_DISPELLING                  26
#define IP_CONST_ONHIT_CASTSPELL_GREATER_SPELL_BREACH                27
#define IP_CONST_ONHIT_CASTSPELL_GUST_OF_WIND                        28
#define IP_CONST_ONHIT_CASTSPELL_HAMMER_OF_THE_GODS                  29
#define IP_CONST_ONHIT_CASTSPELL_HARM                                30
#define IP_CONST_ONHIT_CASTSPELL_HOLD_ANIMAL                         31
#define IP_CONST_ONHIT_CASTSPELL_HOLD_MONSTER                        32
#define IP_CONST_ONHIT_CASTSPELL_HOLD_PERSON                         33
#define IP_CONST_ONHIT_CASTSPELL_IMPLOSION                           34
#define IP_CONST_ONHIT_CASTSPELL_INCENDIARY_CLOUD                    35
#define IP_CONST_ONHIT_CASTSPELL_LESSER_DISPEL                       36
#define IP_CONST_ONHIT_CASTSPELL_LESSER_SPELL_BREACH                 38
#define IP_CONST_ONHIT_CASTSPELL_LIGHT                               40
#define IP_CONST_ONHIT_CASTSPELL_LIGHTNING_BOLT                      41
#define IP_CONST_ONHIT_CASTSPELL_MAGIC_MISSILE                       42
#define IP_CONST_ONHIT_CASTSPELL_MASS_BLINDNESS_AND_DEAFNESS         43
#define IP_CONST_ONHIT_CASTSPELL_MASS_CHARM                          44
#define IP_CONST_ONHIT_CASTSPELL_MELFS_ACID_ARROW                    45
#define IP_CONST_ONHIT_CASTSPELL_METEOR_SWARM                        46
#define IP_CONST_ONHIT_CASTSPELL_MIND_FOG                            47
#define IP_CONST_ONHIT_CASTSPELL_PHANTASMAL_KILLER                   49
#define IP_CONST_ONHIT_CASTSPELL_POISON                              50
#define IP_CONST_ONHIT_CASTSPELL_POWER_WORD_KILL                     51
#define IP_CONST_ONHIT_CASTSPELL_POWER_WORD_STUN                     52

#define IP_CONST_ONHIT_CASTSPELL_SCARE                               54
#define IP_CONST_ONHIT_CASTSPELL_SEARING_LIGHT                       55
#define IP_CONST_ONHIT_CASTSPELL_SILENCE                             56
#define IP_CONST_ONHIT_CASTSPELL_SLAY_LIVING                         57
#define IP_CONST_ONHIT_CASTSPELL_SLEEP                               58
#define IP_CONST_ONHIT_CASTSPELL_SLOW                                59
#define IP_CONST_ONHIT_CASTSPELL_SOUND_BURST                         60
#define IP_CONST_ONHIT_CASTSPELL_STINKING_CLOUD                      61

#define IP_CONST_ONHIT_CASTSPELL_STORM_OF_VENGEANCE                  63
#define IP_CONST_ONHIT_CASTSPELL_SUNBEAM                             64
#define IP_CONST_ONHIT_CASTSPELL_VAMPIRIC_TOUCH                      65
#define IP_CONST_ONHIT_CASTSPELL_WAIL_OF_THE_BANSHEE                 66
#define IP_CONST_ONHIT_CASTSPELL_WALL_OF_FIRE                        67
#define IP_CONST_ONHIT_CASTSPELL_WEB                                 68
#define IP_CONST_ONHIT_CASTSPELL_WEIRD                               69
#define IP_CONST_ONHIT_CASTSPELL_WORD_OF_FAITH                       70

#define IP_CONST_ONHIT_CASTSPELL_CREEPING_DOOM                       72
#define IP_CONST_ONHIT_CASTSPELL_DESTRUCTION                         73
#define IP_CONST_ONHIT_CASTSPELL_HORRID_WILTING                      74
#define IP_CONST_ONHIT_CASTSPELL_ICE_STORM                           75
#define IP_CONST_ONHIT_CASTSPELL_NEGATIVE_ENERGY_BURST               76
#define IP_CONST_ONHIT_CASTSPELL_EVARDS_BLACK_TENTACLES              77
#define IP_CONST_ONHIT_CASTSPELL_ACTIVATE_ITEM                       78
#define IP_CONST_ONHIT_CASTSPELL_FLARE                               79
#define IP_CONST_ONHIT_CASTSPELL_BOMBARDMENT                         80
#define IP_CONST_ONHIT_CASTSPELL_ACID_SPLASH                         81
#define IP_CONST_ONHIT_CASTSPELL_QUILLFIRE                           82
#define IP_CONST_ONHIT_CASTSPELL_EARTHQUAKE                          83
#define IP_CONST_ONHIT_CASTSPELL_SUNBURST                            84
#define IP_CONST_ONHIT_CASTSPELL_BANISHMENT                          85
#define IP_CONST_ONHIT_CASTSPELL_INFLICT_MINOR_WOUNDS                86
#define IP_CONST_ONHIT_CASTSPELL_INFLICT_LIGHT_WOUNDS                87
#define IP_CONST_ONHIT_CASTSPELL_INFLICT_MODERATE_WOUNDS             88
#define IP_CONST_ONHIT_CASTSPELL_INFLICT_SERIOUS_WOUNDS              89
#define IP_CONST_ONHIT_CASTSPELL_INFLICT_CRITICAL_WOUNDS             90
#define IP_CONST_ONHIT_CASTSPELL_BALAGARNSIRONHORN                   91
#define IP_CONST_ONHIT_CASTSPELL_DROWN                               92
#define IP_CONST_ONHIT_CASTSPELL_ELECTRIC_JOLT                       93
#define IP_CONST_ONHIT_CASTSPELL_FIREBRAND                           94
#define IP_CONST_ONHIT_CASTSPELL_WOUNDING_WHISPERS                   95
#define IP_CONST_ONHIT_CASTSPELL_UNDEATHS_ETERNAL_FOE                96
#define IP_CONST_ONHIT_CASTSPELL_INFERNO                             97
#define IP_CONST_ONHIT_CASTSPELL_ISAACS_LESSER_MISSILE_STORM         98
#define IP_CONST_ONHIT_CASTSPELL_ISAACS_GREATER_MISSILE_STORM        99
#define IP_CONST_ONHIT_CASTSPELL_BANE                                100
#define IP_CONST_ONHIT_CASTSPELL_SPIKE_GROWTH                        101
#define IP_CONST_ONHIT_CASTSPELL_TASHAS_HIDEOUS_LAUGHTER             102
#define IP_CONST_ONHIT_CASTSPELL_BIGBYS_INTERPOSING_HAND             103
#define IP_CONST_ONHIT_CASTSPELL_BIGBYS_FORCEFUL_HAND                104
#define IP_CONST_ONHIT_CASTSPELL_BIGBYS_GRASPING_HAND                105
#define IP_CONST_ONHIT_CASTSPELL_BIGBYS_CLENCHED_FIST                106
#define IP_CONST_ONHIT_CASTSPELL_BIGBYS_CRUSHING_HAND                107
#define IP_CONST_ONHIT_CASTSPELL_FLESH_TO_STONE                      108
#define IP_CONST_ONHIT_CASTSPELL_STONE_TO_FLESH                      109
#define IP_CONST_ONHIT_CASTSPELL_CRUMBLE                             110
#define IP_CONST_ONHIT_CASTSPELL_INFESTATION_OF_MAGGOTS              111
#define IP_CONST_ONHIT_CASTSPELL_GREAT_THUNDERCLAP                   112
#define IP_CONST_ONHIT_CASTSPELL_BALL_LIGHTNING                      113
#define IP_CONST_ONHIT_CASTSPELL_GEDLEES_ELECTRIC_LOOP               114
#define IP_CONST_ONHIT_CASTSPELL_HORIZIKAULS_BOOM                    115
#define IP_CONST_ONHIT_CASTSPELL_MESTILS_ACID_BREATH                 116
#define IP_CONST_ONHIT_CASTSPELL_SCINTILLATING_SPHERE                117
#define IP_CONST_ONHIT_CASTSPELL_UNDEATH_TO_DEATH                    118
#define IP_CONST_ONHIT_CASTSPELL_STONEHOLD                           119

#define IP_CONST_ONHIT_CASTSPELL_EVIL_BLIGHT                         121
#define IP_CONST_ONHIT_CASTSPELL_ONHIT_TELEPORT                      122
#define IP_CONST_ONHIT_CASTSPELL_ONHIT_SLAYRAKSHASA                  123
#define IP_CONST_ONHIT_CASTSPELL_ONHIT_FIREDAMAGE                    124
#define IP_CONST_ONHIT_CASTSPELL_ONHIT_UNIQUEPOWER                   125
#define IP_CONST_ONHIT_CASTSPELL_ONHIT_PLANARRIFT                    126
#define IP_CONST_ONHIT_CASTSPELL_ONHIT_DARKFIRE                      127
#define IP_CONST_ONHIT_CASTSPELL_ONHIT_EXTRACTBRAIN                  128
#define IP_CONST_ONHIT_CASTSPELL_ONHITFLAMINGSKIN                    129
#define IP_CONST_ONHIT_CASTSPELL_ONHIT_CHAOSSHIELD                   130
#define IP_CONST_ONHIT_CASTSPELL_ONHIT_CONSTRICTWEAPON               131
#define IP_CONST_ONHIT_CASTSPELL_ONHITRUINARMORBEBILITH              132
#define IP_CONST_ONHIT_CASTSPELL_ONHITDEMILICHTOUCH                  133
#define IP_CONST_ONHIT_CASTSPELL_ONHITDRACOLICHTOUCH                 134
#define IP_CONST_ONHIT_CASTSPELL_INTELLIGENT_WEAPON_ONHIT            135
#define IP_CONST_ONHIT_CASTSPELL_PARALYZE_2                          136
#define IP_CONST_ONHIT_CASTSPELL_DEAFENING_CLNG                      137
#define IP_CONST_ONHIT_CASTSPELL_KNOCKDOWN                           138
#define IP_CONST_ONHIT_CASTSPELL_FREEZE                              139
#define IP_CONST_ONHIT_CASTSPELL_COMBUST                             140

#define IP_CONST_POISON_1D2_STRDAMAGE                0
#define IP_CONST_POISON_1D2_DEXDAMAGE                1
#define IP_CONST_POISON_1D2_CONDAMAGE                2
#define IP_CONST_POISON_1D2_INTDAMAGE                3
#define IP_CONST_POISON_1D2_WISDAMAGE                4
#define IP_CONST_POISON_1D2_CHADAMAGE                5
#define IP_CONST_QUALITY_UNKOWN                      0
#define IP_CONST_QUALITY_DESTROYED                   1
#define IP_CONST_QUALITY_RUINED                      2
#define IP_CONST_QUALITY_VERY_POOR                   3
#define IP_CONST_QUALITY_POOR                        4
#define IP_CONST_QUALITY_BELOW_AVERAGE               5
#define IP_CONST_QUALITY_AVERAGE                     6
#define IP_CONST_QUALITY_ABOVE_AVERAGE               7
#define IP_CONST_QUALITY_GOOD                        8
#define IP_CONST_QUALITY_VERY_GOOD                   9
#define IP_CONST_QUALITY_EXCELLENT                   10
#define IP_CONST_QUALITY_MASTERWORK                  11
#define IP_CONST_QUALITY_GOD_LIKE                    12
#define IP_CONST_QUALITY_RAW                         13
#define IP_CONST_QUALITY_CUT                         14
#define IP_CONST_QUALITY_POLISHED                    15
#define IP_CONST_CONTAINERWEIGHTRED_20_PERCENT       1
#define IP_CONST_CONTAINERWEIGHTRED_40_PERCENT       2
#define IP_CONST_CONTAINERWEIGHTRED_60_PERCENT       3
#define IP_CONST_CONTAINERWEIGHTRED_80_PERCENT       4
#define IP_CONST_CONTAINERWEIGHTRED_100_PERCENT      5
#define IP_CONST_DAMAGERESIST_5                      1
#define IP_CONST_DAMAGERESIST_10                     2
#define IP_CONST_DAMAGERESIST_15                     3
#define IP_CONST_DAMAGERESIST_20                     4
#define IP_CONST_DAMAGERESIST_25                     5
#define IP_CONST_DAMAGERESIST_30                     6
#define IP_CONST_DAMAGERESIST_35                     7
#define IP_CONST_DAMAGERESIST_40                     8
#define IP_CONST_DAMAGERESIST_45                     9
#define IP_CONST_DAMAGERESIST_50                     10
#define IP_CONST_SAVEVS_ACID                         1
#define IP_CONST_SAVEVS_COLD                         3
#define IP_CONST_SAVEVS_DEATH                        4
#define IP_CONST_SAVEVS_DISEASE                      5
#define IP_CONST_SAVEVS_DIVINE                       6
#define IP_CONST_SAVEVS_ELECTRICAL                   7
#define IP_CONST_SAVEVS_FEAR                         8
#define IP_CONST_SAVEVS_FIRE                         9
#define IP_CONST_SAVEVS_MINDAFFECTING                11
#define IP_CONST_SAVEVS_NEGATIVE                     12
#define IP_CONST_SAVEVS_POISON                       13
#define IP_CONST_SAVEVS_POSITIVE                     14
#define IP_CONST_SAVEVS_SONIC                        15
#define IP_CONST_SAVEVS_UNIVERSAL                    0
#define IP_CONST_SAVEBASETYPE_FORTITUDE              1
#define IP_CONST_SAVEBASETYPE_WILL                   2
#define IP_CONST_SAVEBASETYPE_REFLEX                 3
#define IP_CONST_DAMAGESOAK_5_HP                     1
#define IP_CONST_DAMAGESOAK_10_HP                    2
#define IP_CONST_DAMAGESOAK_15_HP                    3
#define IP_CONST_DAMAGESOAK_20_HP                    4
#define IP_CONST_DAMAGESOAK_25_HP                    5
#define IP_CONST_DAMAGESOAK_30_HP                    6
#define IP_CONST_DAMAGESOAK_35_HP                    7
#define IP_CONST_DAMAGESOAK_40_HP                    8
#define IP_CONST_DAMAGESOAK_45_HP                    9
#define IP_CONST_DAMAGESOAK_50_HP                    10
#define IP_CONST_DAMAGEREDUCTION_1                   0
#define IP_CONST_DAMAGEREDUCTION_2                   1
#define IP_CONST_DAMAGEREDUCTION_3                   2
#define IP_CONST_DAMAGEREDUCTION_4                   3
#define IP_CONST_DAMAGEREDUCTION_5                   4
#define IP_CONST_DAMAGEREDUCTION_6                   5
#define IP_CONST_DAMAGEREDUCTION_7                   6
#define IP_CONST_DAMAGEREDUCTION_8                   7
#define IP_CONST_DAMAGEREDUCTION_9                   8
#define IP_CONST_DAMAGEREDUCTION_10                  9
#define IP_CONST_DAMAGEREDUCTION_11                  10
#define IP_CONST_DAMAGEREDUCTION_12                  11
#define IP_CONST_DAMAGEREDUCTION_13                  12
#define IP_CONST_DAMAGEREDUCTION_14                  13
#define IP_CONST_DAMAGEREDUCTION_15                  14
#define IP_CONST_DAMAGEREDUCTION_16                  15
#define IP_CONST_DAMAGEREDUCTION_17                  16
#define IP_CONST_DAMAGEREDUCTION_18                  17
#define IP_CONST_DAMAGEREDUCTION_19                  18
#define IP_CONST_DAMAGEREDUCTION_20                  19

#define IP_CONST_IMMUNITYSPELL_ACID_FOG                        0
#define IP_CONST_IMMUNITYSPELL_AID                             1
#define IP_CONST_IMMUNITYSPELL_BARKSKIN                        2
#define IP_CONST_IMMUNITYSPELL_BESTOW_CURSE                    3
#define IP_CONST_IMMUNITYSPELL_BLINDNESS_AND_DEAFNESS          6
#define IP_CONST_IMMUNITYSPELL_BURNING_HANDS                   8
#define IP_CONST_IMMUNITYSPELL_CALL_LIGHTNING                  9
#define IP_CONST_IMMUNITYSPELL_CHAIN_LIGHTNING                 12
#define IP_CONST_IMMUNITYSPELL_CHARM_MONSTER                   13
#define IP_CONST_IMMUNITYSPELL_CHARM_PERSON                    14
#define IP_CONST_IMMUNITYSPELL_CHARM_PERSON_OR_ANIMAL          15
#define IP_CONST_IMMUNITYSPELL_CIRCLE_OF_DEATH                 16
#define IP_CONST_IMMUNITYSPELL_CIRCLE_OF_DOOM                  17
#define IP_CONST_IMMUNITYSPELL_CLOUDKILL                       21
#define IP_CONST_IMMUNITYSPELL_COLOR_SPRAY                     22
#define IP_CONST_IMMUNITYSPELL_CONE_OF_COLD                    23
#define IP_CONST_IMMUNITYSPELL_CONFUSION                       24
#define IP_CONST_IMMUNITYSPELL_CONTAGION                       25
#define IP_CONST_IMMUNITYSPELL_CONTROL_UNDEAD                  26
#define IP_CONST_IMMUNITYSPELL_CURE_CRITICAL_WOUNDS            27
#define IP_CONST_IMMUNITYSPELL_CURE_LIGHT_WOUNDS               28
#define IP_CONST_IMMUNITYSPELL_CURE_MINOR_WOUNDS               29
#define IP_CONST_IMMUNITYSPELL_CURE_MODERATE_WOUNDS            30
#define IP_CONST_IMMUNITYSPELL_CURE_SERIOUS_WOUNDS             31
#define IP_CONST_IMMUNITYSPELL_DARKNESS                        32
#define IP_CONST_IMMUNITYSPELL_DAZE                            33
#define IP_CONST_IMMUNITYSPELL_DEATH_WARD                      34
#define IP_CONST_IMMUNITYSPELL_DELAYED_BLAST_FIREBALL          35
#define IP_CONST_IMMUNITYSPELL_DISMISSAL                       36
#define IP_CONST_IMMUNITYSPELL_DISPEL_MAGIC                    37
#define IP_CONST_IMMUNITYSPELL_DOMINATE_ANIMAL                 39
#define IP_CONST_IMMUNITYSPELL_DOMINATE_MONSTER                40
#define IP_CONST_IMMUNITYSPELL_DOMINATE_PERSON                 41
#define IP_CONST_IMMUNITYSPELL_DOOM                            42
#define IP_CONST_IMMUNITYSPELL_ENERGY_DRAIN                    46
#define IP_CONST_IMMUNITYSPELL_ENERVATION                      47
#define IP_CONST_IMMUNITYSPELL_ENTANGLE                        48
#define IP_CONST_IMMUNITYSPELL_FEAR                            49
#define IP_CONST_IMMUNITYSPELL_FEEBLEMIND                      50
#define IP_CONST_IMMUNITYSPELL_FINGER_OF_DEATH                 51
#define IP_CONST_IMMUNITYSPELL_FIRE_STORM                      52
#define IP_CONST_IMMUNITYSPELL_FIREBALL                        53
#define IP_CONST_IMMUNITYSPELL_FLAME_ARROW                     54
#define IP_CONST_IMMUNITYSPELL_FLAME_LASH                      55
#define IP_CONST_IMMUNITYSPELL_FLAME_STRIKE                    56
#define IP_CONST_IMMUNITYSPELL_FREEDOM_OF_MOVEMENT             57
#define IP_CONST_IMMUNITYSPELL_GREASE                          59
#define IP_CONST_IMMUNITYSPELL_GREATER_DISPELLING              60
#define IP_CONST_IMMUNITYSPELL_GREATER_PLANAR_BINDING          62
#define IP_CONST_IMMUNITYSPELL_GREATER_SHADOW_CONJURATION      64
#define IP_CONST_IMMUNITYSPELL_GREATER_SPELL_BREACH            65
#define IP_CONST_IMMUNITYSPELL_HAMMER_OF_THE_GODS              68
#define IP_CONST_IMMUNITYSPELL_HARM                            69
#define IP_CONST_IMMUNITYSPELL_HEAL                            71
#define IP_CONST_IMMUNITYSPELL_HEALING_CIRCLE                  72
#define IP_CONST_IMMUNITYSPELL_HOLD_ANIMAL                     73
#define IP_CONST_IMMUNITYSPELL_HOLD_MONSTER                    74
#define IP_CONST_IMMUNITYSPELL_HOLD_PERSON                     75
#define IP_CONST_IMMUNITYSPELL_IMPLOSION                       78
#define IP_CONST_IMMUNITYSPELL_IMPROVED_INVISIBILITY           79
#define IP_CONST_IMMUNITYSPELL_INCENDIARY_CLOUD                80
#define IP_CONST_IMMUNITYSPELL_INVISIBILITY_PURGE              82
#define IP_CONST_IMMUNITYSPELL_LESSER_DISPEL                   84
#define IP_CONST_IMMUNITYSPELL_LESSER_PLANAR_BINDING           86
#define IP_CONST_IMMUNITYSPELL_LESSER_SPELL_BREACH             88
#define IP_CONST_IMMUNITYSPELL_LIGHTNING_BOLT                  91
#define IP_CONST_IMMUNITYSPELL_MAGIC_MISSILE                   97
#define IP_CONST_IMMUNITYSPELL_MASS_BLINDNESS_AND_DEAFNESS     100
#define IP_CONST_IMMUNITYSPELL_MASS_CHARM                      101
#define IP_CONST_IMMUNITYSPELL_MASS_HEAL                       104
#define IP_CONST_IMMUNITYSPELL_MELFS_ACID_ARROW                105
#define IP_CONST_IMMUNITYSPELL_METEOR_SWARM                    106
#define IP_CONST_IMMUNITYSPELL_MIND_FOG                        108
#define IP_CONST_IMMUNITYSPELL_MORDENKAINENS_DISJUNCTION       112
#define IP_CONST_IMMUNITYSPELL_PHANTASMAL_KILLER               116
#define IP_CONST_IMMUNITYSPELL_PLANAR_BINDING                  117
#define IP_CONST_IMMUNITYSPELL_POISON                          118
#define IP_CONST_IMMUNITYSPELL_POWER_WORD_KILL                 120
#define IP_CONST_IMMUNITYSPELL_POWER_WORD_STUN                 121
#define IP_CONST_IMMUNITYSPELL_PRISMATIC_SPRAY                 124
#define IP_CONST_IMMUNITYSPELL_RAY_OF_ENFEEBLEMENT             131
#define IP_CONST_IMMUNITYSPELL_RAY_OF_FROST                    132
#define IP_CONST_IMMUNITYSPELL_SCARE                           142
#define IP_CONST_IMMUNITYSPELL_SEARING_LIGHT                   143
#define IP_CONST_IMMUNITYSPELL_SHADES                          145
#define IP_CONST_IMMUNITYSPELL_SHADOW_CONJURATION              146
#define IP_CONST_IMMUNITYSPELL_SILENCE                         150
#define IP_CONST_IMMUNITYSPELL_SLAY_LIVING                     151
#define IP_CONST_IMMUNITYSPELL_SLEEP                           152
#define IP_CONST_IMMUNITYSPELL_SLOW                            153
#define IP_CONST_IMMUNITYSPELL_SOUND_BURST                     154
#define IP_CONST_IMMUNITYSPELL_STINKING_CLOUD                  158
#define IP_CONST_IMMUNITYSPELL_STONESKIN                       159
#define IP_CONST_IMMUNITYSPELL_STORM_OF_VENGEANCE              160
#define IP_CONST_IMMUNITYSPELL_SUNBEAM                         161
#define IP_CONST_IMMUNITYSPELL_VIRTUE                          165
#define IP_CONST_IMMUNITYSPELL_WAIL_OF_THE_BANSHEE             166
#define IP_CONST_IMMUNITYSPELL_WEB                             167
#define IP_CONST_IMMUNITYSPELL_WEIRD                           168
#define IP_CONST_IMMUNITYSPELL_WORD_OF_FAITH                   169
#define IP_CONST_IMMUNITYSPELL_MAGIC_CIRCLE_AGAINST_ALIGNMENT  171
#define IP_CONST_IMMUNITYSPELL_EAGLE_SPLEDOR                   173
#define IP_CONST_IMMUNITYSPELL_OWLS_WISDOM                     174
#define IP_CONST_IMMUNITYSPELL_FOXS_CUNNING                    175
#define IP_CONST_IMMUNITYSPELL_GREATER_EAGLES_SPLENDOR         176
#define IP_CONST_IMMUNITYSPELL_GREATER_OWLS_WISDOM             177
#define IP_CONST_IMMUNITYSPELL_GREATER_FOXS_CUNNING            178
#define IP_CONST_IMMUNITYSPELL_GREATER_BULLS_STRENGTH          179
#define IP_CONST_IMMUNITYSPELL_GREATER_CATS_GRACE              180
#define IP_CONST_IMMUNITYSPELL_GREATER_ENDURANCE               181
#define IP_CONST_IMMUNITYSPELL_AURA_OF_VITALITY                182
#define IP_CONST_IMMUNITYSPELL_WAR_CRY                         183
#define IP_CONST_IMMUNITYSPELL_REGENERATE                      184
#define IP_CONST_IMMUNITYSPELL_EVARDS_BLACK_TENTACLES          185
#define IP_CONST_IMMUNITYSPELL_LEGEND_LORE                     186
#define IP_CONST_IMMUNITYSPELL_FIND_TRAPS                      187
#define IP_CONST_SPELLLEVEL_0                        0 // hmm are these necessary?
#define IP_CONST_SPELLLEVEL_1                        1
#define IP_CONST_SPELLLEVEL_2                        2
#define IP_CONST_SPELLLEVEL_3                        3
#define IP_CONST_SPELLLEVEL_4                        4
#define IP_CONST_SPELLLEVEL_5                        5
#define IP_CONST_SPELLLEVEL_6                        6
#define IP_CONST_SPELLLEVEL_7                        7
#define IP_CONST_SPELLLEVEL_8                        8
#define IP_CONST_SPELLLEVEL_9                        9
#define IP_CONST_CASTSPELL_ACID_FOG_11                       0
#define IP_CONST_CASTSPELL_ACID_SPLASH_1                     355
#define IP_CONST_CASTSPELL_ACTIVATE_ITEM                     359
#define IP_CONST_CASTSPELL_AID_3                             1
#define IP_CONST_CASTSPELL_AMPLIFY_5                         373
#define IP_CONST_CASTSPELL_ANIMATE_DEAD_10                   3
#define IP_CONST_CASTSPELL_ANIMATE_DEAD_15                   4
#define IP_CONST_CASTSPELL_ANIMATE_DEAD_5                    2
#define IP_CONST_CASTSPELL_AURA_OF_VITALITY_13               321
#define IP_CONST_CASTSPELL_AURA_VERSUS_ALIGNMENT_15          287
#define IP_CONST_CASTSPELL_AURAOFGLORY_7                     360
#define IP_CONST_CASTSPELL_AWAKEN_9                          303
#define IP_CONST_CASTSPELL_BALAGARNSIRONHORN_7               367
#define IP_CONST_CASTSPELL_BANE_5                            380
#define IP_CONST_CASTSPELL_BANISHMENT_15                     361
#define IP_CONST_CASTSPELL_BARKSKIN_12                       7
#define IP_CONST_CASTSPELL_BARKSKIN_3                        5
#define IP_CONST_CASTSPELL_BARKSKIN_6                        6
#define IP_CONST_CASTSPELL_BESTOW_CURSE_5                    8
#define IP_CONST_CASTSPELL_BIGBYS_CLENCHED_FIST_20           393
#define IP_CONST_CASTSPELL_BIGBYS_CRUSHING_HAND_20           394
#define IP_CONST_CASTSPELL_BIGBYS_FORCEFUL_HAND_15           391
#define IP_CONST_CASTSPELL_BIGBYS_GRASPING_HAND_17           392
#define IP_CONST_CASTSPELL_BIGBYS_INTERPOSING_HAND_15        390
#define IP_CONST_CASTSPELL_BLADE_BARRIER_11                  9
#define IP_CONST_CASTSPELL_BLADE_BARRIER_15                  10
#define IP_CONST_CASTSPELL_BLESS_2                           11
#define IP_CONST_CASTSPELL_BLINDNESS_DEAFNESS_3              14
#define IP_CONST_CASTSPELL_BLOOD_FRENZY_7                    353
#define IP_CONST_CASTSPELL_BOMBARDMENT_20                    354
#define IP_CONST_CASTSPELL_BULLS_STRENGTH_10                 16
#define IP_CONST_CASTSPELL_BULLS_STRENGTH_15                 17
#define IP_CONST_CASTSPELL_BULLS_STRENGTH_3                  15
#define IP_CONST_CASTSPELL_BURNING_HANDS_2                   18
#define IP_CONST_CASTSPELL_BURNING_HANDS_5                   19
#define IP_CONST_CASTSPELL_CALL_LIGHTNING_10                 21
#define IP_CONST_CASTSPELL_CALL_LIGHTNING_5                  20
#define IP_CONST_CASTSPELL_CAMOFLAGE_5                       352
#define IP_CONST_CASTSPELL_CATS_GRACE_10                     26
#define IP_CONST_CASTSPELL_CATS_GRACE_15                     27
#define IP_CONST_CASTSPELL_CATS_GRACE_3                      25
#define IP_CONST_CASTSPELL_CHAIN_LIGHTNING_11                28
#define IP_CONST_CASTSPELL_CHAIN_LIGHTNING_15                29
#define IP_CONST_CASTSPELL_CHAIN_LIGHTNING_20                30
#define IP_CONST_CASTSPELL_CHARM_MONSTER_10                  32
#define IP_CONST_CASTSPELL_CHARM_MONSTER_5                   31
#define IP_CONST_CASTSPELL_CHARM_PERSON_10                   34
#define IP_CONST_CASTSPELL_CHARM_PERSON_2                    33
#define IP_CONST_CASTSPELL_CHARM_PERSON_OR_ANIMAL_10         36
#define IP_CONST_CASTSPELL_CHARM_PERSON_OR_ANIMAL_3          35
#define IP_CONST_CASTSPELL_CIRCLE_OF_DEATH_11                37
#define IP_CONST_CASTSPELL_CIRCLE_OF_DEATH_15                38
#define IP_CONST_CASTSPELL_CIRCLE_OF_DEATH_20                39
#define IP_CONST_CASTSPELL_CIRCLE_OF_DOOM_15                 41
#define IP_CONST_CASTSPELL_CIRCLE_OF_DOOM_20                 42
#define IP_CONST_CASTSPELL_CIRCLE_OF_DOOM_9                  40
#define IP_CONST_CASTSPELL_CLAIRAUDIENCE_CLAIRVOYANCE_10     44
#define IP_CONST_CASTSPELL_CLAIRAUDIENCE_CLAIRVOYANCE_15     45
#define IP_CONST_CASTSPELL_CLAIRAUDIENCE_CLAIRVOYANCE_5      43
#define IP_CONST_CASTSPELL_CLARITY_3                         46
#define IP_CONST_CASTSPELL_CLOUDKILL_9                       48
#define IP_CONST_CASTSPELL_COLOR_SPRAY_2                     49
#define IP_CONST_CASTSPELL_CONE_OF_COLD_15                   51
#define IP_CONST_CASTSPELL_CONE_OF_COLD_9                    50
#define IP_CONST_CASTSPELL_CONFUSION_10                      53
#define IP_CONST_CASTSPELL_CONFUSION_5                       52
#define IP_CONST_CASTSPELL_CONTAGION_5                       54
#define IP_CONST_CASTSPELL_CONTINUAL_FLAME_7                 350
#define IP_CONST_CASTSPELL_CONTROL_UNDEAD_13                 55
#define IP_CONST_CASTSPELL_CONTROL_UNDEAD_20                 56
#define IP_CONST_CASTSPELL_CREATE_GREATER_UNDEAD_15          57
#define IP_CONST_CASTSPELL_CREATE_GREATER_UNDEAD_16          58
#define IP_CONST_CASTSPELL_CREATE_GREATER_UNDEAD_18          59
#define IP_CONST_CASTSPELL_CREATE_UNDEAD_11                  60
#define IP_CONST_CASTSPELL_CREATE_UNDEAD_14                  61
#define IP_CONST_CASTSPELL_CREATE_UNDEAD_16                  62
#define IP_CONST_CASTSPELL_CREEPING_DOOM_13                  304
#define IP_CONST_CASTSPELL_CURE_CRITICAL_WOUNDS_12           64
#define IP_CONST_CASTSPELL_CURE_CRITICAL_WOUNDS_15           65
#define IP_CONST_CASTSPELL_CURE_CRITICAL_WOUNDS_7            63
#define IP_CONST_CASTSPELL_CURE_LIGHT_WOUNDS_2               66
#define IP_CONST_CASTSPELL_CURE_LIGHT_WOUNDS_5               67
#define IP_CONST_CASTSPELL_CURE_MINOR_WOUNDS_1               68
#define IP_CONST_CASTSPELL_CURE_MODERATE_WOUNDS_10           71
#define IP_CONST_CASTSPELL_CURE_MODERATE_WOUNDS_3            69
#define IP_CONST_CASTSPELL_CURE_MODERATE_WOUNDS_6            70
#define IP_CONST_CASTSPELL_CURE_SERIOUS_WOUNDS_10            73
#define IP_CONST_CASTSPELL_CURE_SERIOUS_WOUNDS_5             72
#define IP_CONST_CASTSPELL_DARKNESS_3                        75
#define IP_CONST_CASTSPELL_DARKVISION_3                      305
#define IP_CONST_CASTSPELL_DARKVISION_6                      306
#define IP_CONST_CASTSPELL_DAZE_1                            76
#define IP_CONST_CASTSPELL_DEATH_WARD_7                      77
#define IP_CONST_CASTSPELL_DELAYED_BLAST_FIREBALL_13         78
#define IP_CONST_CASTSPELL_DELAYED_BLAST_FIREBALL_15         79
#define IP_CONST_CASTSPELL_DELAYED_BLAST_FIREBALL_20         80
#define IP_CONST_CASTSPELL_DESTRUCTION_13                    307
#define IP_CONST_CASTSPELL_DIRGE_15                          376
#define IP_CONST_CASTSPELL_DISMISSAL_12                      82
#define IP_CONST_CASTSPELL_DISMISSAL_18                      83
#define IP_CONST_CASTSPELL_DISMISSAL_7                       81
#define IP_CONST_CASTSPELL_DISPEL_MAGIC_10                   85
#define IP_CONST_CASTSPELL_DISPEL_MAGIC_5                    84
#define IP_CONST_CASTSPELL_DISPLACEMENT_9                    389
#define IP_CONST_CASTSPELL_DIVINE_FAVOR_5                    345
#define IP_CONST_CASTSPELL_DIVINE_MIGHT_5                    395
#define IP_CONST_CASTSPELL_DIVINE_POWER_7                    86
#define IP_CONST_CASTSPELL_DIVINE_SHIELD_5                   396
#define IP_CONST_CASTSPELL_DOMINATE_ANIMAL_5                 87
#define IP_CONST_CASTSPELL_DOMINATE_MONSTER_17               88
#define IP_CONST_CASTSPELL_DOMINATE_PERSON_7                 89
#define IP_CONST_CASTSPELL_DOOM_2                            90
#define IP_CONST_CASTSPELL_DOOM_5                            91
#define IP_CONST_CASTSPELL_DRAGON_BREATH_ACID_10             400
#define IP_CONST_CASTSPELL_DRAGON_BREATH_COLD_10             401
#define IP_CONST_CASTSPELL_DRAGON_BREATH_FEAR_10             402
#define IP_CONST_CASTSPELL_DRAGON_BREATH_FIRE_10             403
#define IP_CONST_CASTSPELL_DRAGON_BREATH_GAS_10              404
#define IP_CONST_CASTSPELL_DRAGON_BREATH_LIGHTNING_10        405
#define IP_CONST_CASTSPELL_DRAGON_BREATH_PARALYZE_10         406
#define IP_CONST_CASTSPELL_DRAGON_BREATH_SLEEP_10            407
#define IP_CONST_CASTSPELL_DRAGON_BREATH_SLOW_10             408
#define IP_CONST_CASTSPELL_DRAGON_BREATH_WEAKEN_10           409
#define IP_CONST_CASTSPELL_DROWN_15                          368
#define IP_CONST_CASTSPELL_EAGLE_SPLEDOR_10                  289
#define IP_CONST_CASTSPELL_EAGLE_SPLEDOR_15                  290
#define IP_CONST_CASTSPELL_EAGLE_SPLEDOR_3                   288
#define IP_CONST_CASTSPELL_EARTHQUAKE_20                     357
#define IP_CONST_CASTSPELL_ELECTRIC_JOLT_1                   370
#define IP_CONST_CASTSPELL_ELEMENTAL_SHIELD_12               93
#define IP_CONST_CASTSPELL_ELEMENTAL_SHIELD_7                92
#define IP_CONST_CASTSPELL_ELEMENTAL_SWARM_17                94
#define IP_CONST_CASTSPELL_ENDURANCE_10                      96
#define IP_CONST_CASTSPELL_ENDURANCE_15                      97
#define IP_CONST_CASTSPELL_ENDURANCE_3                       95
#define IP_CONST_CASTSPELL_ENDURE_ELEMENTS_2                 98
#define IP_CONST_CASTSPELL_ENERGY_BUFFER_11                  311
#define IP_CONST_CASTSPELL_ENERGY_BUFFER_15                  312
#define IP_CONST_CASTSPELL_ENERGY_BUFFER_20                  313
#define IP_CONST_CASTSPELL_ENERGY_DRAIN_17                   99
#define IP_CONST_CASTSPELL_ENERVATION_7                      100
#define IP_CONST_CASTSPELL_ENTANGLE_2                        101
#define IP_CONST_CASTSPELL_ENTANGLE_5                        102
#define IP_CONST_CASTSPELL_ENTROPIC_SHIELD_5                 349
#define IP_CONST_CASTSPELL_ETHEREAL_VISAGE_15                196
#define IP_CONST_CASTSPELL_ETHEREAL_VISAGE_9                 195
#define IP_CONST_CASTSPELL_ETHEREALNESS_18                   374
#define IP_CONST_CASTSPELL_EVARDS_BLACK_TENTACLES_15         325
#define IP_CONST_CASTSPELL_EVARDS_BLACK_TENTACLES_7          324
#define IP_CONST_CASTSPELL_EXPEDITIOUS_RETREAT_5             387
#define IP_CONST_CASTSPELL_FEAR_5                            103
#define IP_CONST_CASTSPELL_FEEBLEMIND_9                      104
#define IP_CONST_CASTSPELL_FIND_TRAPS_3                      327
#define IP_CONST_CASTSPELL_FINGER_OF_DEATH_13                105
#define IP_CONST_CASTSPELL_FIRE_STORM_13                     106
#define IP_CONST_CASTSPELL_FIRE_STORM_18                     107
#define IP_CONST_CASTSPELL_FIREBALL_10                       109
#define IP_CONST_CASTSPELL_FIREBALL_5                        108
#define IP_CONST_CASTSPELL_FIREBRAND_15                      371
#define IP_CONST_CASTSPELL_FLAME_ARROW_12                    111
#define IP_CONST_CASTSPELL_FLAME_ARROW_18                    112
#define IP_CONST_CASTSPELL_FLAME_ARROW_5                     110
#define IP_CONST_CASTSPELL_FLAME_LASH_10                     114
#define IP_CONST_CASTSPELL_FLAME_LASH_3                      113
#define IP_CONST_CASTSPELL_FLAME_STRIKE_12                   116
#define IP_CONST_CASTSPELL_FLAME_STRIKE_18                   117
#define IP_CONST_CASTSPELL_FLAME_STRIKE_7                    115
#define IP_CONST_CASTSPELL_FLARE_1                           347
#define IP_CONST_CASTSPELL_FLESH_TO_STONE_5                  398
#define IP_CONST_CASTSPELL_FOXS_CUNNING_10                   295
#define IP_CONST_CASTSPELL_FOXS_CUNNING_15                   296
#define IP_CONST_CASTSPELL_FOXS_CUNNING_3                    294
#define IP_CONST_CASTSPELL_FREEDOM_OF_MOVEMENT_7             118
#define IP_CONST_CASTSPELL_GATE_17                           119
#define IP_CONST_CASTSPELL_GHOSTLY_VISAGE_15                 194
#define IP_CONST_CASTSPELL_GHOSTLY_VISAGE_3                  192
#define IP_CONST_CASTSPELL_GHOSTLY_VISAGE_9                  193
#define IP_CONST_CASTSPELL_GHOUL_TOUCH_3                     120
#define IP_CONST_CASTSPELL_GLOBE_OF_INVULNERABILITY_11       121
#define IP_CONST_CASTSPELL_GREASE_2                          122
#define IP_CONST_CASTSPELL_GREATER_BULLS_STRENGTH_11         300
#define IP_CONST_CASTSPELL_GREATER_CATS_GRACE_11             301
#define IP_CONST_CASTSPELL_GREATER_DISPELLING_15             124
#define IP_CONST_CASTSPELL_GREATER_DISPELLING_7              123
#define IP_CONST_CASTSPELL_GREATER_EAGLES_SPLENDOR_11        297
#define IP_CONST_CASTSPELL_GREATER_ENDURANCE_11              302
#define IP_CONST_CASTSPELL_GREATER_FOXS_CUNNING_11           299
#define IP_CONST_CASTSPELL_GREATER_MAGIC_FANG_9              384
#define IP_CONST_CASTSPELL_GREATER_OWLS_WISDOM_11            298
#define IP_CONST_CASTSPELL_GREATER_PLANAR_BINDING_15         126
#define IP_CONST_CASTSPELL_GREATER_RESTORATION_13            127
#define IP_CONST_CASTSPELL_GREATER_SHADOW_CONJURATION_9      128
#define IP_CONST_CASTSPELL_GREATER_SPELL_BREACH_11           129
#define IP_CONST_CASTSPELL_GREATER_SPELL_MANTLE_17           130
#define IP_CONST_CASTSPELL_GREATER_STONESKIN_11              131
#define IP_CONST_CASTSPELL_GRENADE_ACID_1                    341
#define IP_CONST_CASTSPELL_GRENADE_CALTROPS_1                343
#define IP_CONST_CASTSPELL_GRENADE_CHICKEN_1                 342
#define IP_CONST_CASTSPELL_GRENADE_CHOKING_1                 339
#define IP_CONST_CASTSPELL_GRENADE_FIRE_1                    336
#define IP_CONST_CASTSPELL_GRENADE_HOLY_1                    338
#define IP_CONST_CASTSPELL_GRENADE_TANGLE_1                  337
#define IP_CONST_CASTSPELL_GRENADE_THUNDERSTONE_1            340
#define IP_CONST_CASTSPELL_GUST_OF_WIND_10                   410
#define IP_CONST_CASTSPELL_HAMMER_OF_THE_GODS_12             134
#define IP_CONST_CASTSPELL_HAMMER_OF_THE_GODS_7              133
#define IP_CONST_CASTSPELL_HARM_11                           136
#define IP_CONST_CASTSPELL_HASTE_10                          138
#define IP_CONST_CASTSPELL_HASTE_5                           137
#define IP_CONST_CASTSPELL_HEAL_11                           139
#define IP_CONST_CASTSPELL_HEALING_CIRCLE_16                 141
#define IP_CONST_CASTSPELL_HEALING_CIRCLE_9                  140
#define IP_CONST_CASTSPELL_HOLD_ANIMAL_3                     142
#define IP_CONST_CASTSPELL_HOLD_MONSTER_7                    143
#define IP_CONST_CASTSPELL_HOLD_PERSON_3                     144
#define IP_CONST_CASTSPELL_HORRID_WILTING_15                 308
#define IP_CONST_CASTSPELL_HORRID_WILTING_20                 309
#define IP_CONST_CASTSPELL_ICE_STORM_9                       310
#define IP_CONST_CASTSPELL_IDENTIFY_3                        147
#define IP_CONST_CASTSPELL_IMPLOSION_17                      148
#define IP_CONST_CASTSPELL_IMPROVED_INVISIBILITY_7           149
#define IP_CONST_CASTSPELL_INCENDIARY_CLOUD_15               150
#define IP_CONST_CASTSPELL_INFERNO_15                        377
#define IP_CONST_CASTSPELL_INFLICT_CRITICAL_WOUNDS_12        366
#define IP_CONST_CASTSPELL_INFLICT_LIGHT_WOUNDS_5            363
#define IP_CONST_CASTSPELL_INFLICT_MINOR_WOUNDS_1            362
#define IP_CONST_CASTSPELL_INFLICT_MODERATE_WOUNDS_7         364
#define IP_CONST_CASTSPELL_INFLICT_SERIOUS_WOUNDS_9          365
#define IP_CONST_CASTSPELL_INVISIBILITY_3                    151
#define IP_CONST_CASTSPELL_INVISIBILITY_PURGE_5              152
#define IP_CONST_CASTSPELL_INVISIBILITY_SPHERE_5             153
#define IP_CONST_CASTSPELL_ISAACS_GREATER_MISSILE_STORM_15   379
#define IP_CONST_CASTSPELL_ISAACS_LESSER_MISSILE_STORM_13    378
#define IP_CONST_CASTSPELL_KNOCK_3                           154
#define IP_CONST_CASTSPELL_LEGEND_LORE_5                     326
#define IP_CONST_CASTSPELL_LESSER_DISPEL_3                   155
#define IP_CONST_CASTSPELL_LESSER_DISPEL_5                   156
#define IP_CONST_CASTSPELL_LESSER_MIND_BLANK_9               157
#define IP_CONST_CASTSPELL_LESSER_PLANAR_BINDING_9           158
#define IP_CONST_CASTSPELL_LESSER_RESTORATION_3              159
#define IP_CONST_CASTSPELL_LESSER_SPELL_BREACH_7             160
#define IP_CONST_CASTSPELL_LESSER_SPELL_MANTLE_9             161
#define IP_CONST_CASTSPELL_LIGHT_1                           162
#define IP_CONST_CASTSPELL_LIGHT_5                           163
#define IP_CONST_CASTSPELL_LIGHTNING_BOLT_10                 165
#define IP_CONST_CASTSPELL_LIGHTNING_BOLT_5                  164
#define IP_CONST_CASTSPELL_MAGE_ARMOR_2                      167
#define IP_CONST_CASTSPELL_MAGIC_CIRCLE_AGAINST_ALIGNMENT_5  286
#define IP_CONST_CASTSPELL_MAGIC_FANG_5                      383
#define IP_CONST_CASTSPELL_MAGIC_MISSILE_3                   172
#define IP_CONST_CASTSPELL_MAGIC_MISSILE_5                   173
#define IP_CONST_CASTSPELL_MAGIC_MISSILE_9                   174
#define IP_CONST_CASTSPELL_MANIPULATE_PORTAL_STONE           344
#define IP_CONST_CASTSPELL_MASS_BLINDNESS_DEAFNESS_15        179
#define IP_CONST_CASTSPELL_MASS_CAMOFLAGE_13                 386
#define IP_CONST_CASTSPELL_MASS_CHARM_15                     180
#define IP_CONST_CASTSPELL_MASS_HASTE_11                     182
#define IP_CONST_CASTSPELL_MASS_HEAL_15                      183
#define IP_CONST_CASTSPELL_MELFS_ACID_ARROW_3                184
#define IP_CONST_CASTSPELL_MELFS_ACID_ARROW_6                185
#define IP_CONST_CASTSPELL_MELFS_ACID_ARROW_9                186
#define IP_CONST_CASTSPELL_METEOR_SWARM_17                   187
#define IP_CONST_CASTSPELL_MIND_BLANK_15                     188
#define IP_CONST_CASTSPELL_MIND_FOG_9                        189
#define IP_CONST_CASTSPELL_MINOR_GLOBE_OF_INVULNERABILITY_15  191
#define IP_CONST_CASTSPELL_MINOR_GLOBE_OF_INVULNERABILITY_7  190
#define IP_CONST_CASTSPELL_MORDENKAINENS_DISJUNCTION_17      197
#define IP_CONST_CASTSPELL_MORDENKAINENS_SWORD_13            198
#define IP_CONST_CASTSPELL_MORDENKAINENS_SWORD_18            199
#define IP_CONST_CASTSPELL_NATURES_BALANCE_15                200
#define IP_CONST_CASTSPELL_NEGATIVE_ENERGY_BURST_10          315
#define IP_CONST_CASTSPELL_NEGATIVE_ENERGY_BURST_5           314
#define IP_CONST_CASTSPELL_NEGATIVE_ENERGY_PROTECTION_10     202
#define IP_CONST_CASTSPELL_NEGATIVE_ENERGY_PROTECTION_15     203
#define IP_CONST_CASTSPELL_NEGATIVE_ENERGY_PROTECTION_5      201
#define IP_CONST_CASTSPELL_NEGATIVE_ENERGY_RAY_1             316
#define IP_CONST_CASTSPELL_NEGATIVE_ENERGY_RAY_3             317
#define IP_CONST_CASTSPELL_NEGATIVE_ENERGY_RAY_5             318
#define IP_CONST_CASTSPELL_NEGATIVE_ENERGY_RAY_7             319
#define IP_CONST_CASTSPELL_NEGATIVE_ENERGY_RAY_9             320
#define IP_CONST_CASTSPELL_NEUTRALIZE_POISON_5               204
#define IP_CONST_CASTSPELL_ONE_WITH_THE_LAND_7               351
#define IP_CONST_CASTSPELL_OWLS_INSIGHT_15                   369
#define IP_CONST_CASTSPELL_OWLS_WISDOM_10                    292
#define IP_CONST_CASTSPELL_OWLS_WISDOM_15                    293
#define IP_CONST_CASTSPELL_OWLS_WISDOM_3                     291
#define IP_CONST_CASTSPELL_PHANTASMAL_KILLER_7               205
#define IP_CONST_CASTSPELL_PLANAR_ALLY_15                    382
#define IP_CONST_CASTSPELL_PLANAR_BINDING_11                 206
#define IP_CONST_CASTSPELL_POISON_5                          207
#define IP_CONST_CASTSPELL_POLYMORPH_SELF_7                  208
#define IP_CONST_CASTSPELL_POWER_WORD_KILL_17                209
#define IP_CONST_CASTSPELL_POWER_WORD_STUN_13                210
#define IP_CONST_CASTSPELL_PRAYER_5                          211
#define IP_CONST_CASTSPELL_PREMONITION_15                    212
#define IP_CONST_CASTSPELL_PRISMATIC_SPRAY_13                213
#define IP_CONST_CASTSPELL_PROTECTION_FROM_ALIGNMENT_2       284
#define IP_CONST_CASTSPELL_PROTECTION_FROM_ALIGNMENT_5       285
#define IP_CONST_CASTSPELL_PROTECTION_FROM_ELEMENTS_10       217
#define IP_CONST_CASTSPELL_PROTECTION_FROM_ELEMENTS_3        216
#define IP_CONST_CASTSPELL_PROTECTION_FROM_SPELLS_13         224
#define IP_CONST_CASTSPELL_PROTECTION_FROM_SPELLS_20         225
#define IP_CONST_CASTSPELL_QUILLFIRE_8                       356
#define IP_CONST_CASTSPELL_RAISE_DEAD_9                      226
#define IP_CONST_CASTSPELL_RAY_OF_ENFEEBLEMENT_2             227
#define IP_CONST_CASTSPELL_RAY_OF_FROST_1                    228
#define IP_CONST_CASTSPELL_REGENERATE_13                     323
#define IP_CONST_CASTSPELL_REMOVE_BLINDNESS_DEAFNESS_5       229
#define IP_CONST_CASTSPELL_REMOVE_CURSE_5                    230
#define IP_CONST_CASTSPELL_REMOVE_DISEASE_5                  231
#define IP_CONST_CASTSPELL_REMOVE_FEAR_2                     232
#define IP_CONST_CASTSPELL_REMOVE_PARALYSIS_3                233
#define IP_CONST_CASTSPELL_RESIST_ELEMENTS_10                235
#define IP_CONST_CASTSPELL_RESIST_ELEMENTS_3                 234
#define IP_CONST_CASTSPELL_RESISTANCE_2                      236
#define IP_CONST_CASTSPELL_RESISTANCE_5                      237
#define IP_CONST_CASTSPELL_RESTORATION_7                     238
#define IP_CONST_CASTSPELL_RESURRECTION_13                   239
#define IP_CONST_CASTSPELL_ROGUES_CUNNING_3                  328
#define IP_CONST_CASTSPELL_SANCTUARY_2                       240
#define IP_CONST_CASTSPELL_SCARE_2                           241
#define IP_CONST_CASTSPELL_SEARING_LIGHT_5                   242
#define IP_CONST_CASTSPELL_SEE_INVISIBILITY_3                243
#define IP_CONST_CASTSPELL_SHADES_11                         244
#define IP_CONST_CASTSPELL_SHADOW_CONJURATION_7              245
#define IP_CONST_CASTSPELL_SHADOW_SHIELD_13                  246
#define IP_CONST_CASTSPELL_SHAPECHANGE_17                    247
#define IP_CONST_CASTSPELL_SHIELD_5                          348
#define IP_CONST_CASTSPELL_SHIELD_OF_FAITH_5                 381
#define IP_CONST_CASTSPELL_SILENCE_3                         249
#define IP_CONST_CASTSPELL_SLAY_LIVING_9                     250
#define IP_CONST_CASTSPELL_SLEEP_2                           251
#define IP_CONST_CASTSPELL_SLEEP_5                           252
#define IP_CONST_CASTSPELL_SLOW_5                            253
#define IP_CONST_CASTSPELL_SOUND_BURST_3                     254
#define IP_CONST_CASTSPELL_SPECIAL_ALCOHOL_BEER              330
#define IP_CONST_CASTSPELL_SPECIAL_ALCOHOL_SPIRITS           332
#define IP_CONST_CASTSPELL_SPECIAL_ALCOHOL_WINE              331
#define IP_CONST_CASTSPELL_SPECIAL_HERB_BELLADONNA           333
#define IP_CONST_CASTSPELL_SPECIAL_HERB_GARLIC               334
#define IP_CONST_CASTSPELL_SPELL_MANTLE_13                   257
#define IP_CONST_CASTSPELL_SPELL_RESISTANCE_15               256
#define IP_CONST_CASTSPELL_SPELL_RESISTANCE_9                255
#define IP_CONST_CASTSPELL_SPIKE_GROWTH_9                    385
#define IP_CONST_CASTSPELL_STINKING_CLOUD_5                  259
#define IP_CONST_CASTSPELL_STONE_TO_FLESH_5                  399
#define IP_CONST_CASTSPELL_STONESKIN_7                       260
#define IP_CONST_CASTSPELL_STORM_OF_VENGEANCE_17             261
#define IP_CONST_CASTSPELL_SUMMON_CREATURE_I_2               262
#define IP_CONST_CASTSPELL_SUMMON_CREATURE_I_5               263
#define IP_CONST_CASTSPELL_SUMMON_CREATURE_II_3              264
#define IP_CONST_CASTSPELL_SUMMON_CREATURE_III_5             265
#define IP_CONST_CASTSPELL_SUMMON_CREATURE_IV_7              266
#define IP_CONST_CASTSPELL_SUMMON_CREATURE_IX_17             267
#define IP_CONST_CASTSPELL_SUMMON_CREATURE_V_9               268
#define IP_CONST_CASTSPELL_SUMMON_CREATURE_VI_11             269
#define IP_CONST_CASTSPELL_SUMMON_CREATURE_VII_13            270
#define IP_CONST_CASTSPELL_SUMMON_CREATURE_VIII_15           271
#define IP_CONST_CASTSPELL_SUNBEAM_13                        272
#define IP_CONST_CASTSPELL_SUNBURST_20                       358
#define IP_CONST_CASTSPELL_TASHAS_HIDEOUS_LAUGHTER_7         388
#define IP_CONST_CASTSPELL_TENSERS_TRANSFORMATION_11         273
#define IP_CONST_CASTSPELL_TIME_STOP_17                      274
#define IP_CONST_CASTSPELL_TRUE_SEEING_9                     275
#define IP_CONST_CASTSPELL_TRUE_STRIKE_5                     346
#define IP_CONST_CASTSPELL_UNDEATHS_ETERNAL_FOE_20           375
#define IP_CONST_CASTSPELL_UNIQUE_POWER                      329
#define IP_CONST_CASTSPELL_UNIQUE_POWER_SELF_ONLY            335
#define IP_CONST_CASTSPELL_VAMPIRIC_TOUCH_5                  277
#define IP_CONST_CASTSPELL_VIRTUE_1                          278
#define IP_CONST_CASTSPELL_WAIL_OF_THE_BANSHEE_17            279
#define IP_CONST_CASTSPELL_WALL_OF_FIRE_9                    280
#define IP_CONST_CASTSPELL_WAR_CRY_7                         322
#define IP_CONST_CASTSPELL_WEB_3                             281
#define IP_CONST_CASTSPELL_WEIRD_17                          282
#define IP_CONST_CASTSPELL_WORD_OF_FAITH_13                  283
#define IP_CONST_CASTSPELL_WOUNDING_WHISPERS_9               372
#define IP_CONST_SPELLSCHOOL_ABJURATION                      0
#define IP_CONST_SPELLSCHOOL_CONJURATION                     1
#define IP_CONST_SPELLSCHOOL_DIVINATION                      2
#define IP_CONST_SPELLSCHOOL_ENCHANTMENT                     3
#define IP_CONST_SPELLSCHOOL_EVOCATION                       4
#define IP_CONST_SPELLSCHOOL_ILLUSION                        5
#define IP_CONST_SPELLSCHOOL_NECROMANCY                      6
#define IP_CONST_SPELLSCHOOL_TRANSMUTATION                   7
#define IP_CONST_SPELLRESISTANCEBONUS_10                     0
#define IP_CONST_SPELLRESISTANCEBONUS_12                     1
#define IP_CONST_SPELLRESISTANCEBONUS_14                     2
#define IP_CONST_SPELLRESISTANCEBONUS_16                     3
#define IP_CONST_SPELLRESISTANCEBONUS_18                     4
#define IP_CONST_SPELLRESISTANCEBONUS_20                     5
#define IP_CONST_SPELLRESISTANCEBONUS_22                     6
#define IP_CONST_SPELLRESISTANCEBONUS_24                     7
#define IP_CONST_SPELLRESISTANCEBONUS_26                     8
#define IP_CONST_SPELLRESISTANCEBONUS_28                     9
#define IP_CONST_SPELLRESISTANCEBONUS_30                     10
#define IP_CONST_SPELLRESISTANCEBONUS_32                     11
#define IP_CONST_TRAPTYPE_SPIKE                              1
#define IP_CONST_TRAPTYPE_HOLY                               2
#define IP_CONST_TRAPTYPE_TANGLE                             3
#define IP_CONST_TRAPTYPE_BLOBOFACID                         4
#define IP_CONST_TRAPTYPE_FIRE                               5
#define IP_CONST_TRAPTYPE_ELECTRICAL                         6
#define IP_CONST_TRAPTYPE_GAS                                7
#define IP_CONST_TRAPTYPE_FROST                              8
#define IP_CONST_TRAPTYPE_ACID_SPLASH                        9
#define IP_CONST_TRAPTYPE_SONIC                              10
#define IP_CONST_TRAPTYPE_NEGATIVE                           11
#define IP_CONST_TRAPSTRENGTH_MINOR                          0
#define IP_CONST_TRAPSTRENGTH_AVERAGE                        1
#define IP_CONST_TRAPSTRENGTH_STRONG                         2
#define IP_CONST_TRAPSTRENGTH_DEADLY                         3
#define IP_CONST_REDUCEDWEIGHT_80_PERCENT                    1
#define IP_CONST_REDUCEDWEIGHT_60_PERCENT                    2
#define IP_CONST_REDUCEDWEIGHT_40_PERCENT                    3
#define IP_CONST_REDUCEDWEIGHT_20_PERCENT                    4
#define IP_CONST_REDUCEDWEIGHT_10_PERCENT                    5
#define IP_CONST_WEIGHTINCREASE_5_LBS                        0
#define IP_CONST_WEIGHTINCREASE_10_LBS                       1
#define IP_CONST_WEIGHTINCREASE_15_LBS                       2
#define IP_CONST_WEIGHTINCREASE_30_LBS                       3
#define IP_CONST_WEIGHTINCREASE_50_LBS                       4
#define IP_CONST_WEIGHTINCREASE_100_LBS                      5
#define IP_CONST_CLASS_BARBARIAN                             0
#define IP_CONST_CLASS_BARD                                  1
#define IP_CONST_CLASS_CLERIC                                2
#define IP_CONST_CLASS_DRUID                                 3
#define IP_CONST_CLASS_FIGHTER                               4
#define IP_CONST_CLASS_MONK                                  5
#define IP_CONST_CLASS_PALADIN                               6
#define IP_CONST_CLASS_RANGER                                7
#define IP_CONST_CLASS_ROGUE                                 8
#define IP_CONST_CLASS_SORCERER                              9
#define IP_CONST_CLASS_WIZARD                                10
#define IP_CONST_ARCANE_SPELL_FAILURE_MINUS_50_PERCENT        0
#define IP_CONST_ARCANE_SPELL_FAILURE_MINUS_45_PERCENT        1
#define IP_CONST_ARCANE_SPELL_FAILURE_MINUS_40_PERCENT        2
#define IP_CONST_ARCANE_SPELL_FAILURE_MINUS_35_PERCENT        3
#define IP_CONST_ARCANE_SPELL_FAILURE_MINUS_30_PERCENT        4
#define IP_CONST_ARCANE_SPELL_FAILURE_MINUS_25_PERCENT        5
#define IP_CONST_ARCANE_SPELL_FAILURE_MINUS_20_PERCENT        6
#define IP_CONST_ARCANE_SPELL_FAILURE_MINUS_15_PERCENT        7
#define IP_CONST_ARCANE_SPELL_FAILURE_MINUS_10_PERCENT        8
#define IP_CONST_ARCANE_SPELL_FAILURE_MINUS_5_PERCENT         9
#define IP_CONST_ARCANE_SPELL_FAILURE_PLUS_5_PERCENT        10
#define IP_CONST_ARCANE_SPELL_FAILURE_PLUS_10_PERCENT       11
#define IP_CONST_ARCANE_SPELL_FAILURE_PLUS_15_PERCENT       12
#define IP_CONST_ARCANE_SPELL_FAILURE_PLUS_20_PERCENT       13
#define IP_CONST_ARCANE_SPELL_FAILURE_PLUS_25_PERCENT       14
#define IP_CONST_ARCANE_SPELL_FAILURE_PLUS_30_PERCENT       15
#define IP_CONST_ARCANE_SPELL_FAILURE_PLUS_35_PERCENT       16
#define IP_CONST_ARCANE_SPELL_FAILURE_PLUS_40_PERCENT       17
#define IP_CONST_ARCANE_SPELL_FAILURE_PLUS_45_PERCENT       18
#define IP_CONST_ARCANE_SPELL_FAILURE_PLUS_50_PERCENT       19
    
#endif /* _NX_NWN_CONST_ITEMPROP_H_ */

/* vim: set sw4: */
