#ifndef NWNX_COMBAT_CONSTS_H
#define NWNX_COMBAT_CONSTS_H

#define COMBAT_TARGET_STATE_BLIND            0x1
#define COMBAT_TARGET_STATE_ATTACKER_INVIS   0x2
#define COMBAT_TARGET_STATE_UNSEEN           0x4
#define COMBAT_TARGET_STATE_MOVING           0x8
#define COMBAT_TARGET_STATE_PRONE            0x10
#define COMBAT_TARGET_STATE_STUNNED          0x20
#define COMBAT_TARGET_STATE_FLANKED          0x40
#define COMBAT_TARGET_STATE_FLATFOOTED       0x80
#define COMBAT_TARGET_STATE_ASLEEP           0x100
#define COMBAT_TARGET_STATE_ATTACKER_UNSEEN  0x200
#define COMBAT_TARGET_STATE_INVIS            0x400

#define SITUATION_INDEX_COUPDEGRACE   0
#define SITUATION_INDEX_SNEAK_ATTACK  1
#define SITUATION_INDEX_DEATH_ATTACK  2

#define SITUATION_FLAG_COUPDEGRACE   ( 1 << SITUATION_INDEX_COUPDEGRACE )
#define SITUATION_FLAG_SNEAK_ATTACK  ( 1 << SITUATION_INDEX_SNEAK_ATTACK )
#define SITUATION_FLAG_DEATH_ATTACK  ( 1 << SITUATION_INDEX_DEATH_ATTACK )

#define SITUATION_NUM           3
#define SKILL_NUM               28
#define ABILITY_NUM             6
#define COMBAT_MOD_NUM          8

#define WEAPON_FEAT_2DA "wpnfeats"
#define WEAPON_PROP_2DA "wpnprops"

#define WEAPON_TYPE_NORMAL     0
#define WEAPON_TYPE_BOW        1
#define WEAPON_TYPE_SLING      2
#define WEAPON_TYPE_CROSSBOW   3
#define WEAPON_TYPE_SHURIKEN   4
#define WEAPON_TYPE_DART       5
#define WEAPON_TYPE_THROWAXE   6
#define WEAPON_TYPE_DOUBLE     7
#define WEAPON_TYPE_UNARMED    8

#define DAMAGE_POWER_NUM       21
#define DAMAGE_INDEX_NUM       13

#define EQUIP_TYPE_ONHAND      0
#define EQUIP_TYPE_OFFHAND     1
#define EQUIP_TYPE_UNARMED     2
#define EQUIP_TYPE_CREATURE_1  3
#define EQUIP_TYPE_CREATURE_2  4
#define EQUIP_TYPE_CREATURE_3  5
#define EQUIP_TYPE_NUM         6

#define MAXIMUM_ATTACKS        6

const int NWNX_COMBAT_INFO_INVALID       = 0;
const int NWNX_COMBAT_INFO_ARMOR_CLASS   = 0x1;
const int NWNX_COMBAT_INFO_HITPOINTS     = 0x2;
const int NWNX_COMBAT_INFO_CONCEALMENT   = 0x4;
const int NWNX_COMBAT_INFO_RESISTANCE    = 0x8;
const int NWNX_COMBAT_INFO_REDUCTION     = 0x10;
const int NWNX_COMBAT_INFO_IMMUNITY      = 0x20;

const int NWNX_COMBAT_INFO_WEAPONS       = 0x40;
const int NWNX_COMBAT_INFO_ATTACKS       = 0x80;
const int NWNX_COMBAT_INFO_IMMUNITY_MISC = 0x100;

const int NWNX_COMBAT_INFO_OFFENSE     = ( NWNX_COMBAT_INFO_ATTACKS |
					   NWNX_COMBAT_INFO_WEAPONS );

const int NWNX_COMBAT_INFO_DEFENSE     = ( NWNX_COMBAT_INFO_ARMOR_CLASS |
					   NWNX_COMBAT_INFO_HITPOINTS   |
					   NWNX_COMBAT_INFO_CONCEALMENT |
					   NWNX_COMBAT_INFO_REDUCTION   |
					   NWNX_COMBAT_INFO_RESISTANCE  |
					   NWNX_COMBAT_INFO_IMMUNITY );

#endif // NWNX_COMBAT_CONSTS_H
