#ifndef _CNWSMODULE_H_
#define _CNWSMODULE_H_
#include "nwndef.h"
#include "CExoString.h"
#include "CResRef.h"
#include "CResIFO.h"
#include "CExoLocString.h"
#include "CExoArrayList.h"
#include "CGameObject.h"
#include "CExoLinkedList.h"
#include "CNWSPlayerTURD.h"
#include "CNWSScriptVarTable.h"

class CNWSModule : public CResHelper<CResIFO>, CGameObject
{
public:
    int AIUpdate();
    void AddObjectToLimbo(unsigned long);
    int AddObjectToLookupTable(CExoString, unsigned long);
    int AddTURDsToWorld();
    void AddToTURDList(CNWSPlayerTURD *);
    int AddWorldJournalEntryStrref(unsigned long, unsigned long, unsigned long, unsigned long);
    void AddWorldJournalEntry(int, CExoString, CExoString, unsigned long, unsigned long);
    CNWSModule * AsNWSModule();
    void CleanUpLimboList();
    int ClearAreaVisitedFlags();
    int ComputeInterAreaPath(CPathfindInformation *);
    int DeleteWorldJournalAllEntries();
    void DeleteWorldJournalEntryStrref(unsigned long);
    void DeleteWorldJournalEntry(int);
    void DoUpdate();
    void EventHandler(unsigned long, unsigned long, void *, unsigned long, unsigned long);
    unsigned long FindObjectByTagOrdinal(CExoString const &, unsigned long);
    unsigned long FindObjectByTagTypeOrdinal(CExoString const &, int, unsigned long);
    int FindTagPositionInTable(char *);
    int GenerateInterAreaDFSSuccessors(int, CPathfindInformation *, unsigned long **);
    int GetAreaByName(CExoString &);
    CNWSArea * GetAreaByTag(CExoString &);
    int GetAreaList();
    CNWSArea * GetArea(CResRef);
    CNWSArea * GetArea(unsigned long);
    int GetCustomScriptEventId();
    int GetDawnHour();
    int GetDuskHour();
    int GetEnableScriptDebugger();
    unsigned char * GetFullCipher(CExoString);
    int GetInvisibleCreaturesList();
    int GetIsDigitalDistributionDemo();
    int GetIsNWMFile();
    int GetIsSaveGame();
    int GetLastEnter();
    int GetLastExit();
    int GetLastItemAcquiredBy();
    int GetLastItemAcquiredFrom();
    int GetLastItemAcquiredStackSize();
    int GetLastItemAcquired();
    int GetLastItemActivatedArea();
    int GetLastItemActivatedPosition();
    int GetLastItemActivatedTarget();
    int GetLastItemActivated();
    int GetLastItemActivator();
    int GetLastItemLoser();
    int GetLastItemLostStackSize();
    int GetLastItemLost();
    int GetLastPCCancelCutscene();
    int GetLastPCLevellingUp();
    int GetLastPlayerChatMessageType();
    CExoString GetLastPlayerChatMessage();
    int GetLastPlayerChatObject();
    int GetLastPlayerDied();
    int GetLastPlayerDying();
    int GetLastRespawnButtonPresser();
    int GetLastRestEventType();
    int GetLastRested();
    int GetLimboArray();
    int GetMaxHenchmen();
    int GetMinutesPerHour();
    CExoLocString GetModuleDescription();
    int GetModuleEntryInfo();
    CExoLocString GetModuleName();
    CExoString GetNWMResName();
    int GetPCItemLastEquippedBy();
    int GetPCItemLastEquipped();
    int GetPCItemLastUnequippedBy();
    int GetPCItemLastUnequipped();
    unsigned long GetPlayerIndexInPlayerList(CNWSPlayer *);
    int GetPlayerPathfindRule();
    CNWSPlayerTURD * GetPlayerTURDFromList(CNWSPlayer *);
    unsigned long GetPrimaryPlayerIndex();
    int GetScriptName(int);
    CNWSScriptVarTable * GetScriptVarTable();
    int GetStartMovie();
    CExoString GetTag();
    int GetTimeOfDayState();
    void GetTime(unsigned long *, unsigned long *, unsigned long *, unsigned long *, unsigned char *, unsigned long *);
    unsigned long GetWaypoint(CExoString const &);
    unsigned long GetWorldJournalIndexUnique();
    int GetXPScale();
    int InterAreaDFS(int, int, CPathfindInformation *);
    int IsObjectInLimbo(unsigned long);
    unsigned char IsOfficialCampaign();
    int LoadLimboCreatures(CResGFF *, CResStruct *, int);
    unsigned long LoadModuleFinish();
    unsigned long LoadModuleInProgress(int, int);
    unsigned long LoadModuleStart(CExoString, int);
    void LoadTURDList(CResGFF *, CResStruct *);
    void PackModuleIntoMessage(unsigned long);
    void PackPlayerCharacterListIntoMessage(CNWSPlayer *, CExoArrayList<NWPlayerCharacterList_st *> &);
    unsigned long PlotInterAreaPath(CPathfindInformation *, unsigned long);
    unsigned long PlotPathInArea(CPathfindInformation *, unsigned long);
    unsigned long PlotPath(CPathfindInformation *, unsigned long);
    void PostProcess();
    void RemoveFromTURDList(CNWSPlayer *);
    void RemoveObjectFromLimbo(unsigned long);
    int RemoveObjectFromLookupTable(CExoString, unsigned long);
    void SaveLimboCreatures(CResGFF *, CResStruct *);
    int SaveModuleFAC(CERFFile *);
    int SaveModuleFinish(CExoString &, CExoString &);
    int SaveModuleIFOFinish(CResGFF *, CResStruct *, CERFFile *, CExoString &, CExoArrayList<unsigned long> &);
    int SaveModuleIFOStart(CResGFF *, CResStruct *);
    int SaveModuleInProgress();
    void SaveModuleStart(CExoString &, CExoString &);
    int SavePlayers(CResGFF *, CResStruct *, CExoString &, CExoArrayList<unsigned long> &);
    int SaveStatic(CERFFile *, CExoString, unsigned short, int);
    int SaveTURDList(CResGFF *, CResStruct *);
    int SetCustomScriptEventId(int);
    int SetEnableScriptDebugger(unsigned char);
    void SetIntraAreaGoal(CPathfindInformation *);
    int SetIsNWMFile(int);
    int SetIsSaveGame(int);
    int SetLastEnter(unsigned long);
    int SetLastExit(unsigned long);
    int SetLastItemAcquiredBy(unsigned long);
    int SetLastItemAcquiredFrom(unsigned long);
    int SetLastItemAcquiredStackSize(int);
    int SetLastItemAcquired(unsigned long);
    int SetLastItemActivatedArea(unsigned long);
    int SetLastItemActivatedPosition(Vector const &);
    int SetLastItemActivatedTarget(unsigned long);
    int SetLastItemActivated(unsigned long);
    int SetLastItemActivator(unsigned long);
    int SetLastItemLoser(unsigned long);
    int SetLastItemLostStackSize(int);
    int SetLastItemLost(unsigned long);
    int SetLastPCCancelCutscene(unsigned long);
    int SetLastPCLevellingUp(unsigned long);
    int SetLastPlayerChatMessageType(unsigned char);
    int SetLastPlayerChatMessage(CExoString const &);
    int SetLastPlayerChatObject(unsigned long);
    int SetLastPlayerDied(unsigned long);
    int SetLastPlayerDying(unsigned long);
    int SetLastRespawnButtonPresser(unsigned long);
    int SetLastRestEventType(unsigned char);
    int SetLastRested(unsigned long);
    int SetMaxHenchmen(int);
    int SetNWMResName(CExoString &);
    int SetPCItemLastEquippedBy(unsigned long);
    int SetPCItemLastEquipped(unsigned long);
    int SetPCItemLastUnequippedBy(unsigned long);
    int SetPCItemLastUnequipped(unsigned long);
    int SetPlayerPathfindRule(unsigned char);
    void SetScriptName(int, CExoString);
    int SetXPScale(unsigned char);
    void TimeStopSanityCheck();
    int UnloadModule();
    void UpdateTime(unsigned long, unsigned long, unsigned long);
    ~CNWSModule();
    CNWSModule(CExoString, int, int);

    /* 0x2C/44 */ CExoLinkedList<NWModuleExpansion_st> field_2C;
    /* 0x30/48 */ CExoLinkedList<NWModuleCutScene_st> field_30;
    /* 0x34/52 */ CExoLinkedList<CResRef> field_34;
    /* (mtype:CExoArrayList<unsigned long>) */
    /* 0x38/56 */ CExoArrayList<unsigned long> Areas;
    /* 0x44/68 */ unsigned long CurrentAreaIndex;
    /* 0x48/72 */ CExoLinkedList<NWPlayerListItem_st> field_48;
    /* (mtype:CExoLinkedList<CNWSPlayerTURD>) */
    /* 0x4C/76 */ CExoLinkedList<CNWSPlayerTURD> TURDList;
    /* 0x/ */ CExoLocString Description;
    /* 0x58/88 */ CExoString m_sCustomTLK;
    /* 0x60/ */ unsigned long field_60;
    /* 0x64/ */ unsigned long ModuleEntryInfo;
    /* 0x68/ */ CExoString CurrentGame;
    /* 0x70/128 */ char rsvd2[12];
    /* 0x7C/ */ unsigned long IsDemo;
    /* 0x80/128 */ unsigned long field_80;
    /* 0x84/132 */ CExoLocString Name;
    /* (mtype:CExoArrayList<CExoString>) */
    /* 0x8C/140 */ CExoArrayList<CExoString> HakList;
    /* 0x98/ */ CResRef SomeResref;
    /* 0xA8/ */ CNWSScriptVarTable VarTable;
    /* 0xB8/184 */ char rsvd3[12];
    /* 0xBC/188 */ CExoString Scripts[18];
    /* 0x14C/ */ unsigned long field_14C;
    /* 0x150/ */ CExoArrayList<CNWSTagNode> TagList;
    /* 0x15C/ */ CExoArrayList<unsigned long> InvisibleCreaturesList;
    /* 0x168/ */ unsigned long CustomScriptEventId;
    /* 0x16C/ */ unsigned long LastEntered;
    /* 0x170/ */ unsigned long LastExited;
    /* 0x174/ */ unsigned long LastItemAcquired;
    /* 0x178/ */ unsigned long LastItemAcquiredFrom;
    /* 0x17C/ */ unsigned long LastItemAcquiredBy;
    /* 0x180/ */ unsigned long LastItemLost;
    /* 0x184/ */ unsigned long LastItemLoser;
    /* 0x188/ */ unsigned long LastItemAcquiredStackSize;
    /* 0x18C/ */ unsigned long LastItemLostStackSize;
    /* 0x190/ */ nwobjid PCItemLastEquipped;
    /* 0x194/ */ nwobjid PCItemLastEquippedBy;
    /* 0x198/ */ nwobjid PCItemLastUnequipped;
    /* 0x19C/ */ nwobjid PCItemLastUnequippedBy;
    /* 0x1A0/ */ unsigned long LastRested;
    /* 0x1A4/ */ unsigned long LastRestedType;
    /* 0x1A8/ */ unsigned long LastPlayerDied;
    /* 0x1AC/ */ unsigned long LastPlayerDying;
    /* 0x1B0/ */ unsigned long LastRespawner;
    /* 0x1B4/ */ unsigned long LastItemActivated;
    /* 0x1B8/ */ unsigned long LastItemActivatedActivator;
    /* 0x1BC/ */ unsigned long LastItemActivatedArea;
    /* 0x1C0/ */ unsigned long LastItemActivatedTarget;
    /* 0x1C4/ */ unsigned long DateYear;
    /* 0x1C8/ */ unsigned long DateMonth;
    /* 0x1CC/ */ unsigned long DateDay;
    /* 0x1D0/ */ unsigned long TimeHour;
    /* 0x1D4/ */ nwobjid LastPCCancelCutscene;
    /* 0x1D8/ */ uint8_t MinutesPerHour;
    /* 0x1D9/ */ uint8_t DawnHour;
    /* 0x1DA/ */ uint8_t DuskHour;
    /* 0x1DB/ */ uint8_t StartMonth;
    /* 0x1DC/ */ uint8_t StartDay;
    /* 0x1DD/ */ uint8_t StartHour;
    /* 0x1DE/ */ uint8_t XPScale;
    /* 0x1DF/ */ uint8_t field_1DF;
    /* 0x1E0/ */ unsigned long StaryYear;
    /* 0x1E4/ */ unsigned long field_1E4;
    /* 0x1E8/ */ unsigned long field_1E8;
    /* 0x1EC/ */ unsigned long field_1EC;
    /* 0x1F0/ */ unsigned long field_1F0;
    /* 0x1F4/ */ uint8_t TimeOfDayState;
    /* 0x1F5/ */ uint8_t field_1F5;
    /* 0x1F6/ */ uint8_t field_1F6;
    /* 0x1F7/ */ uint8_t field_1F7;
    /* 0x1F8/ */ unsigned long field_1F8;
    /* 0x1FC/ */ unsigned long field_1FC;
    /* 0x200/ */ unsigned long IsSaveGame;
    /* 0x204/ */ CExoArrayList<void*> WorldJournalEntries;
    /* 0x210/ */ uint8_t field_210;
    /* 0x211/ */ uint8_t field_211;
    /* 0x212/ */ uint8_t field_212;
    /* 0x213/ */ uint8_t field_213;
    /* 0x214/ */ unsigned long MaxHenchmen;
    /* 0x218/ */ CExoArrayList<unsigned long> LimboObjects;
    /* 0x224/ */ unsigned long SaveGameERF;
    /* 0x228/ */ unsigned long field_228;
    /* 0x22C/ */ unsigned long field_22C;
    /* 0x230/ */ unsigned long field_230;
    /* 0x234/ */ CExoString Tag;
    /* 0x23C/ */ unsigned long IsNWMFile;
    /* 0x240/ */ CExoString NWMResName;
    /* 0x248/ */ unsigned long CExoTableCount;
    /* 0x24C/ */ uint8_t PCPathFindRule;
    /* 0x24D/ */ uint8_t EnableScriptDebugger;
    /* 0x24E/ */ uint8_t field_24E;
    /* 0x24F/ */ uint8_t field_24F;
    /* 0x250/ */ unsigned long LastPCChatObject;
    /* 0x254/ */ CExoString LastPCChatMessage;
    /* 0x25C/ */ unsigned long LastPCChatType;
};

static_assert_size(CNWSModule, 0x260);

#endif
