#ifndef _CNWSPLACEABLE_H_
#define _CNWSPLACEABLE_H_
#include "nwndef.h"
#include "CNWSObject.h"
#include "Vector.h"
#include "CExoString.h"
#include "CResRef.h"
#include "CExoLocString.h"

class CNWSPlaceable : public CNWSObject
{
public:
    unsigned long AIActionCastSpell(CNWSObjectActionNode *);
    void AIUpdate();
    int AcquireItem(CNWSItem **, unsigned long, unsigned char, unsigned char, int);
    unsigned long AcquireItemsFromObject(unsigned long, int);
    int AddCastSpellActions(unsigned long, int, Vector, unsigned long, int, unsigned char);
    void AddToArea(CNWSArea *, float, float, float, int);
    CNWSPlaceable * AsNWSPlaceable();
    void CalculateActionPoints();
    void CloseInventory(unsigned long, int);
    void ClosePlaceableForAllPlayers();
    void DoDamage(int);
    int DropItemsIntoArea();
    void EventHandler(unsigned long, unsigned long, void *, unsigned long, unsigned long);
    int GetActive();
    int GetAppearance();
    int GetAutoRemoveKey();
    int GetBaseType();
    int GetBearing();
    unsigned short GetBodyBagAppearance();
    int GetBodyBag();
    int GetCloseLockDC();
    int GetCreatureList();
    int GetCurrentItemContainer();
    CExoString GetDescriptionOverride();
    CExoLocString & GetDescription();
    int GetDetectDC();
    int GetDetectable();
    CResRef GetDialogResref();
    int GetDieWhenEmpty();
    int GetDisarmDC();
    int GetDisarmable();
    CExoString GetDisplayName();
    unsigned long GetEffectSpellId();
    int GetFactionId();
    CExoLocString & GetFirstName();
    int GetFlagged();
    int GetFortSave();
    int GetHardness();
    int GetHasInventory();
    int GetIsBodyBag();
    int GetIsGroundPile();
    int GetItemContainerArrayIndex();
    unsigned long GetItemCount(int);
    int GetItemRepository();
    int GetKeyName();
    CExoString GetKeyRequiredFeedbackMessage();
    int GetKeyRequired();
    int GetLastClosed();
    int GetLastDefaultClickedBy();
    int GetLastDisarmed();
    int GetLastLocked();
    int GetLastOpened();
    int GetLastTriggered();
    int GetLastUnlocked();
    int GetLastUser();
    int GetLightIsOn();
    int GetLightStateChange();
    int GetLockable();
    int GetLocked();
    int GetLootableCreatureId();
    Vector GetNearestActionPoint(Vector const &);
    int GetNeverMakeIntoStaticObject();
    int GetOneShot();
    int GetOpenLockDC();
    int GetPickable();
    CExoString GetPortalInfo();
    int GetRecoverable();
    int GetReflexSave();
    int GetRepositoryArrayIndex();
    int GetScriptName(int);
    int GetSittingCreature();
    int GetStaticObject();
    int GetTemplateResRef();
    int GetTrapCreator();
    int GetTrapFaction();
    int GetTrapped();
    int GetType();
    int GetUpdateDisplayName();
    int GetUseable();
    int GetWillSave();
    int LoadBodyBag(unsigned short);
    int LoadFromTemplate(CResRef, CExoString *);
    int LoadPlaceable(CResGFF *, CResStruct *, CExoString *);
    void OpenInventory(unsigned long);
    void PostProcess();
    void RemoveFromArea();
    int RemoveItem(CNWSItem *, int);
    int SavePlaceable(CResGFF *, CResStruct *);
    int SetActive(int);
    int SetAppearance(unsigned short);
    int SetAutoRemoveKey(int);
    int SetBaseType(unsigned char);
    int SetBearing(float);
    int SetBodyBag(unsigned char);
    int SetCloseLockDC(unsigned char);
    int SetCurrentItemContainer(unsigned long);
    void SetDescriptionOverride(CExoString);
    void SetDescription(CExoLocString);
    int SetDetectDC(unsigned char);
    int SetDetectable(int);
    void SetDialogResref(CResRef);
    int SetDieWhenEmpty(int);
    int SetDisarmDC(unsigned char);
    int SetDisarmable(int);
    void SetDisplayName(CExoString);
    void SetEffectSpellId(unsigned long);
    int SetFactionId(int);
    void SetFirstName(CExoLocString);
    int SetFlagged(unsigned char);
    int SetFortSave(unsigned char);
    int SetHardness(unsigned char);
    int SetHasInventory(int);
    int SetIsBodyBag(int);
    int SetIsGroundPile(int);
    int SetItemContainerArrayIndex(unsigned short);
    int SetKeyName(CExoString const &);
    void SetKeyRequiredFeedbackMessage(CExoString);
    int SetKeyRequired(int);
    int SetLastClosed(unsigned long);
    int SetLastDefaultClickedBy(unsigned long);
    int SetLastDisarmed(unsigned long);
    int SetLastLocked(unsigned long);
    int SetLastOpened(unsigned long);
    int SetLastTriggered(unsigned long);
    int SetLastUnlocked(unsigned long);
    int SetLastUser(unsigned long);
    void SetLightIsOn(int);
    int SetLightStateChange(int);
    int SetLockable(int);
    int SetLocked(int);
    int SetLootableCreatureId(unsigned long);
    int SetNeverMakeIntoStaticObject(int);
    int SetOneShot(int);
    int SetOpenLockDC(unsigned char);
    void SetOrientation(Vector);
    int SetPickable(int);
    void SetPortalInfo(CExoString);
    int SetRecoverable(int);
    int SetReflexSave(unsigned char);
    int SetRepositoryArrayIndex(unsigned short);
    void SetScriptName(int, CExoString);
    int SetSittingCreature(unsigned long);
    int SetStaticObject(int);
    void SetTemplateResRef(CResRef);
    int SetTrapCreator(unsigned long);
    int SetTrapFaction(int);
    int SetTrapped(int);
    int SetType(unsigned char);
    int SetUpdateDisplayName(int);
    int SetUseable(int);
    int SetWillSave(unsigned char);
    ~CNWSPlaceable();
    CNWSPlaceable(unsigned long);

    /* 0x1C4/452 */ CExoLocString Name;
    /* 0x1CC/460 */ CExoString DisplayName;
    /* 0x1D4/468 */ unsigned long UpdateDisplayName;
    /* 0x1D8/472 */ unsigned short Appearance;
    /* 0x1DA/474 */ unsigned short field_1DA;
    /* 0x1DC/476 */ CExoLocString Description;
    /* 0x1E4/484 */ CExoString DescriptionOverride;
    /* 0x1EC/492 */ unsigned long Faction;
    /* 0x1F0/496 */ CResRef Conversation;
    /* 0x200/512 */ unsigned long field_200;
    /* 0x204/516 */ unsigned long IsGroundPile;
    /* 0x208/520 */ unsigned long SittingObject;
    /* 0x20C/524 */ unsigned long Hardness;
    /* 0x210/528 */ float Bearing;
    /* 0x214/532 */ unsigned long Locked;
    /* 0x218/536 */ CExoString KeyName;
    /* 0x220/544 */ CExoString KeyRequiredMessage;
    /* 0x228/552 */ unsigned long KeyRequired;
    /* 0x22C/556 */ unsigned long AutoRemoveKey;
    /* 0x230/560 */ unsigned char OpenLockDC;
    /* 0x231/561 */ unsigned char CloseLockDC;
    /* 0x232/562 */ unsigned char field_232;
    /* 0x233/563 */ unsigned char field_233;
    /* 0x234/564 */ unsigned long TrapCreator;
    /* 0x238/568 */ unsigned char TrapDetectDC;
    /* 0x239/569 */ unsigned char field_239;
    /* 0x23A/570 */ unsigned char field_23A;
    /* 0x23B/571 */ unsigned char field_23B;
    /* 0x23C/572 */ unsigned long Trapped;
    /* 0x240/576 */ unsigned long TrapDisarmDC;
    /* 0x244/580 */ unsigned long TrapDisarmable;
    /* 0x248/584 */ unsigned long TrapDetectable;
    /* 0x24C/588 */ unsigned long TrapOneShot;
    /* 0x250/592 */ unsigned long TrapRecoverable;
    /* 0x254/596 */ unsigned char TrapFlagged;
    /* 0x255/597 */ unsigned char field_255;
    /* 0x256/598 */ unsigned char field_256;
    /* 0x257/599 */ unsigned char field_257;
    /* 0x258/600 */ unsigned char TrapBaseType;
    /* 0x259/601 */ unsigned char field_259;
    /* 0x25A/602 */ unsigned char field_25A;
    /* 0x25B/603 */ unsigned char field_25B;
    /* 0x25C/604 */ unsigned long TrapActive;
    /* 0x260/608 */ unsigned long TrapFaction;
    /* 0x264/612 */ CExoString OnClosed;
    /* 0x26C/620 */ CExoString OnDamaged;
    /* 0x274/628 */ CExoString OnDeath;
    /* 0x27C/636 */ CExoString OnDisarm;
    /* 0x284/644 */ CExoString OnHeartbeat;
    /* 0x28C/652 */ CExoString OnInvDisturbed;
    /* 0x294/660 */ CExoString OnLock;
    /* 0x29C/668 */ CExoString OnMeleeAttacked;
    /* 0x2A4/676 */ CExoString OnOpen;
    /* 0x2AC/684 */ CExoString OnSpellCastAt;
    /* 0x2B4/692 */ CExoString OnUnlock;
    /* 0x2BC/700 */ CExoString OnUsed;
    /* 0x2C4/708 */ CExoString OnUserDefined;
    /* 0x2CC/716 */ CExoString OnDialog;
    /* 0x2D4/724 */ CExoString OnTrapTriggered;
    /* 0x2DC/732 */ CExoString OnClick;
    /* 0x2E4/740 */ unsigned char SaveFort;
    /* 0x2E5/741 */ unsigned char SaveWill;
    /* 0x2E6/742 */ unsigned char SaveReflex;
    /* 0x2E7/743 */ unsigned char field_2E7;
    /* 0x2E8/744 */ unsigned long CreatureList;
    /* 0x2EC/748 */ unsigned long field_2EC;
    /* 0x2F0/752 */ unsigned long field_2F0;
    /* 0x2F4/756 */ unsigned long HasInventory;
    /* 0x2F8/760 */ unsigned long Useable;
    /* 0x2FC/764 */ unsigned long Pickable;
    /* 0x300/768 */ unsigned long Lockable;
    /* 0x304/772 */ unsigned long DieWhenEmpty;
    /* 0x308/776 */ unsigned long field_308;
    /* 0x30C/780 */ unsigned long field_30C;
    /* 0x310/784 */ unsigned long LootableCreatureId;
    /* 0x314/788 */ unsigned long IsBodyBag;
    /* 0x318/792 */ unsigned long field_318;
    /* 0x31C/796 */ unsigned long field_31C;
    /* 0x320/800 */ unsigned long LastOpener;
    /* 0x324/804 */ unsigned long LastCloser;
    /* 0x328/808 */ unsigned long LastUser;
    /* 0x32C/812 */ unsigned long LastClicker;
    /* 0x330/816 */ unsigned long LastTriggerer;
    /* 0x334/820 */ unsigned long LastDisarmer;
    /* 0x338/824 */ unsigned long LastLocker;
    /* 0x33C/828 */ unsigned long LastUnlocker;
    /* 0x340/832 */ CItemRepository* Inventory;
    /* 0x344/836 */ unsigned short RepositoryArrayIndex;
    /* 0x346/838 */ unsigned short ItemContainerArrayIndex;
    /* 0x348/840 */ unsigned long CurrentItemContainer;
    /* 0x34C/844 */ unsigned long field_34C;
    /* 0x350/848 */ unsigned long field_350;
    /* 0x354/852 */ unsigned long field_354;
    /* 0x358/856 */ unsigned long field_358;
    /* 0x35C/860 */ unsigned long field_35C;
    /* 0x360/864 */ unsigned long field_360;
    /* 0x364/868 */ CResRef TemplateResRef;
    /* 0x374/884 */ CExoString Portal;
    /* 0x37C/892 */ unsigned long EffectSpellId;
    /* 0x380/896 */ unsigned long LightIsOn;
    /* 0x384/900 */ unsigned long LightsUpdate;
    /* 0x388/904 */ unsigned char BodyBag;
    /* 0x389/905 */ unsigned char field_389;
    /* 0x38A/906 */ unsigned char field_38A;
    /* 0x38B/907 */ unsigned char field_38B;
    /* 0x38C/908 */ unsigned long IsStatic;
    /* 0x390/912 */ unsigned long NeverMakeIntoStatic;
};

static_assert_size(CNWSPlaceable, 0x394);

#endif
